# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_homepage:
    path: /
    methods: [GET]
    defaults:
        template: SyliusWebBundle:Frontend/Homepage:main.html.twig
        _controller: sylius.controller.product:indexAction
        _sylius:
            paginate: $perpage
            sortable: true
            sorting:
                updatedAt: desc
            template: $template
            permission: false

sylius_currency:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/currency.yml
    prefix: /currency

sylius_locale:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/locale.yml
    prefix: /locale

sylius_static_content:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/static_content.yml
    prefix: /content

sylius_checkout:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/checkout.yml
    prefix: /checkout

sylius_account:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/account.yml
    prefix: /account

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_cart_summary:
    path: /cart
    defaults:
        _controller: sylius.controller.cart:summaryAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

sylius_cart_save:
    path: /cart/save
    defaults:
        _controller: sylius.controller.cart:saveAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

sylius_contact:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/contact.yml
    prefix: /contact

sylius_search:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/search.yml
    prefix: /search

sylius_user:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/user.yml

furniture_catalog:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/catalog.yml