Furniture\SpecificationBundle\Entity\BuyerImage:
    type: entity
    table: specification_buyer_image

    oneToOne:
        buyer:
            targetEntity: Furniture\SpecificationBundle\Entity\Buyer
            inversedBy: image
            joinColumn:
                name: buyer_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE
