Furniture\SpecificationBundle\Entity\Buyer:
    type: entity
    table: specification_buyer

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    fields:
        createdAt:
            type: datetime
            name: created_at

        firstName:
            type: string
            name: first_name

        secondName:
            type: string
            name: second_name

        email:
            type: string
            name: email
            nullable: true

        address:
            type: string
            name: address
            nullable: true

        phone:
            type: string
            name: phone
            nullable: true

        sale:
            type: float
            name: sale
            
        lat:
            type: float
            name: latitude
            nullable: true
            
        lng:
            type: float
            name: longtitude
            nullable: true
            
        country:
            type: string
            name: Country
            nullable: true
            
        locality:
            type: string
            name: City
            nullable: true
            
        streetNumber:
            type: string
            name: Street number
            nullable: true
            
        route:
            type: string
            name: Street number
            nullable: true
        
        sublocalityLevel1:
            type: string
            nullable: true
            
        sublocalityLevel2:
            type: string
            nullable: true
            
        sublocalityLevel3:
            type: string
            nullable: true
            
        sublocalityLevel4:
            type: string
            nullable: true
            
        sublocalityLevel5:
            type: string
            nullable: true
            
        administrativeAreaLevel1:
            type: string
            nullable: true
            
        administrativeAreaLevel2:
            type: string
            nullable: true
            
        administrativeAreaLevel3:
            type: string
            nullable: true
            
        administrativeAreaLevel4:
            type: string
            nullable: true
            
        administrativeAreaLevel5:
            type: string
            nullable: true

    manyToOne:
        creator:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerUserProfile
            joinColumn:
                name: creator
                referencedColumnName: id
                nullable: true
