Furniture\SpecificationBundle\Entity\Specification:
    type: entity
    table: specification

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            name: name

        description:
            type: text
            name: description
            nullable: true

        createdAt:
            type: datetime
            name: created_at

        updatedAt:
            type: datetime
            name: updated_at

        finishedAt:
            type: datetime
            name: finished_at
            nullable: true

    manyToOne:
        creator:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerUserProfile
            joinColumn:
                name: creator
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false

        buyer:
            targetEntity: Furniture\SpecificationBundle\Entity\Buyer
            joinColumn:
                name: buyer_id
                referencedColumnName: id
                onDelete: SET NULL
                nullable: true

    oneToMany:
        items:
            targetEntity: Furniture\SpecificationBundle\Entity\SpecificationItem
            mappedBy: specification

        sales:
            targetEntity: Furniture\SpecificationBundle\Entity\SpecificationSale
            mappedBy: specification
            orderBy:
                position: ASC

    lifecycleCallbacks:
        preUpdate: [ onUpdate ]
