Furniture\SpecificationBundle\Entity\SpecificationItem:
    type: entity
    table: specification_item

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    oneToOne:
        skuItem:
            targetEntity: Furniture\SpecificationBundle\Entity\SkuSpecificationItem
            mappedBy: specificationItem
            cascade: [ persist ]

    manyToOne:
        specification:
            targetEntity: Furniture\SpecificationBundle\Entity\Specification
            inversedBy: items
            joinColumn:
                name: specification_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

    fields:
        note:
            type: text
            name: note
            nullable: true

        quantity:
            type: integer
            name: quantity

        cost:
            type: integer
            name: cost
            nullable: true

        createdAt:
            type: datetime
            name: created_at

        updatedAt:
            type: datetime
            name: updated_at
            nullable: true

    lifecycleCallbacks:
        preUpdate: [ onUpdate ]