Furniture\SpecificationBundle\Entity\Specification:
    type: entity
    table: specification

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            name: name

        description:
            type: text
            name: description
            nullable: true

        createdAt:
            type: datetime
            name: created_at

        updatedAt:
            type: datetime
            name: updated_at
            nullable: true

        finishedAt:
            type: datetime
            name: finished_at
            nullable: true