Furniture\SpecificationBundle\Entity\Specification:
    type: entity
    table: specification

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            name: name

        description:
            type: text
            name: description
            nullable: true

        createdAt:
            type: datetime
            name: created_at

        updatedAt:
            type: datetime
            name: updated_at
            nullable: true

        finishedAt:
            type: datetime
            name: finished_at
            nullable: true

    manyToOne:
        user:
            targetEntity: Furniture\CommonBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false

        buyer:
            targetEntity: Furniture\SpecificationBundle\Entity\Buyer
            joinColumn:
                name: buyer_id
                referencedColumnName: id
                onDelete: RESTRICT
                nullable: true

    oneToMany:
        items:
            targetEntity: Furniture\SpecificationBundle\Entity\SpecificationItem
            mappedBy: specification

    lifecycleCallbacks:
        preUpdate: [ onUpdate ]
