parameters:
    sylius.form.type.customer_filter.class: Furniture\UserBundle\Form\Type\CustomerFilterType
    security.authentication.form_entry_point.class: Furniture\UserBundle\Security\Authentication\FormAuthenticationEntryPoint
    security.authentication.provider.dao.class: Furniture\UserBundle\Security\Authentication\DaoAuthenticationProvider
    security.authentication.failure_handler.class: Furniture\UserBundle\Security\Authentication\DefaultAuthenticationFailureHandler
    security.authentication.rememberme.services.simplehash.class: Furniture\UserBundle\Security\Authentication\DefaultTokenBasedRememberMeServices

services:
    user.killer.storage:
        class: Furniture\UserBundle\Killer\Storage\MemcachedStorage
        arguments: [ @memcached ]

    user.killer:
        class: Furniture\UserBundle\Killer\Killer
        arguments: [ @user.killer.storage, @request_stack, @security.token_storage ]

    user.killer.subscriber:
        class: Furniture\UserBundle\Killer\Subscriber\CollectSessionSubscriber
        arguments: [ @user.killer ]
        tags:
            - { name: kernel.event_subscriber }

    user.killer.doctrine_subscriber:
        class: Furniture\UserBundle\Killer\Subscriber\UserChangedSubscriber
        arguments: [ @user.killer, @security.token_storage ]
        tags:
            - { name: doctrine.event_subscriber }

    user.password_resetter:
        class: Furniture\UserBundle\PasswordResetter\PasswordResetter
        arguments: [ @doctrine.orm.default_entity_manager, @furniture.mailer ]

    user.email_verifier:
        class: Furniture\UserBundle\Security\EmailVerifier\EmailVerifier
        arguments: [ @doctrine.orm.default_entity_manager, @furniture.mailer ]

    sylius.listener.default_username:
        class: Furniture\UserBundle\EventListener\DefaultUsernameORMListener
        tags:
            - { name: doctrine.event_subscriber }

    security.authentication.failure_handler:
        class: %security.authentication.failure_handler.class%
        arguments:
            - @http_kernel
            - @security.http_utils
            - []
            - @logger
            - @router
            - @user.password_resetter
