services:
    form.type.furniture_retailer_profile:
        class: Furniture\RetailerBundle\Form\Type\RetailerProfileType
        arguments: [ '@google_service.maps.geocoding' ]
        tags:
            - { name: form.type, alias: furniture_retailer_profile }

    # Security voters
    security.voter.retailer_employee_list:
        class: Furniture\RetailerBundle\Security\Voter\RetailerEmployeeListVoter
        tags:
            - { name: security.voter }

    security.voter.retailer_employee_create:
        class: Furniture\RetailerBundle\Security\Voter\RetailerEmployeeCreateVoter
        tags:
            - { name: security.voter }

    security.voter.retailer_employee:
        class: Furniture\RetailerBundle\Security\Voter\RetailerEmployeeVoter
        tags:
            - { name: security.voter }

    security.voter.retailer:
        class: Furniture\RetailerBundle\Security\Voter\RetailerVoter
        tags:
            - { name: security.voter }

    security.voter.retailer_factory_rate:
        class: Furniture\RetailerBundle\Security\Voter\RetailerFactoryRateVoter
        tags:
            - { name: security.voter }

    security.voter.retailer_partners:
        class: Furniture\RetailerBundle\Security\Voter\RetailerPartnersVoter
        tags:
            - { name: security.voter }

    security.voter.retailer_factory_relation:
        class: Furniture\RetailerBundle\Security\Voter\RetailerFactoryRelationVoter
        tags:
            - { name: security.voter }

    twig.extension.retailer:
        class: Furniture\RetailerBundle\Twig\RetailerExtension
        arguments: [ '@retailer_profile.removal_checker.registry' ]
        tags:
            - { name: twig.extension }
