parameters:
    stof_doctrine_extensions.listener.softdeleteable.class: Furniture\CommonBundle\Gedmo\SoftDeletable\SoftDeletableListener
    sylius.templating.helper.money.class: Furniture\CommonBundle\Templating\MoneyHelper

services:
    doctrine.subscriber.uplodable:
        class: Furniture\CommonBundle\Uploadable\UploadableSubscriber
        arguments: [ @sylius.image_uploader ]
        tags:
            - { name: doctrine.event_subscriber }
