parameters:
    stof_doctrine_extensions.listener.softdeleteable.class: Furniture\CommonBundle\Gedmo\SoftDeletable\SoftDeletableListener
    stof_doctrine_extensions.listener.loggable.class: Furniture\CommonBundle\Gedmo\Loggable\LoggableListener
    sylius.templating.helper.money.class: Furniture\CommonBundle\Templating\MoneyHelper
    sylius.form.type.taxon_selection.class: Furniture\CommonBundle\Form\Type\TaxonSelectionType
    sylius.controller.backend.form.class: Furniture\CommonBundle\Controller\Backend\FormController

services:
    doctrine.subscriber.uplodable:
        class: Furniture\CommonBundle\Uploadable\UploadableSubscriber
        arguments: [ @sylius.image_uploader ]
        tags:
            - { name: doctrine.event_subscriber }

    session.handler.native:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler

    twig.extension.common:
        class: Furniture\CommonBundle\Twig\CommonExtension
        tags:
            - { name: twig.extension }
            
    liip_imagine.filter.loader.auto_relative_resize:
        class: Furniture\CommonBundle\Imagine\Filter\Loader\AutoRelativeResizeLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: auto_relative_resize }

    memcached:
        class: Memcached
        calls:
            - [ addServer, [ %memcached.host%, %memcached.port% ]]