Furniture\CompositionBundle\Entity\CompositeImage:
    type: entity
    table: composite_image
    inheritanceType: SINGLE_TABLE
    manyToOne:
        composite:
            targetEntity: Furniture\CompositionBundle\Entity\Composite
            inversedBy: images
            joinColumn:
                cascade: [persist]
                name: composite_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false