Furniture\CompositionBundle\Entity\CompositeCollection:
    type: entity
    table: composition_collection

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            name: name
        position:
            type: integer
            name: position
            nullable: true

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            joinColumn:
                name: factory_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL