Furniture\CompositionBundle\Entity\CompositeCollection:
    type: entity
    table: composition_collection

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            name: name
