# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.hostname = "furniture.dev"
    config.vm.box = "bento/centos-7.1"

    config.vm.provision "puppet_modules", type:"shell", run: "always",  path: "puppet_modules_install.sh"

    config.puppet_install.puppet_version = "3.7.3"
    config.vm.provision "puppet" do |puppet|
        puppet.hiera_config_path = "hiera.yaml"
        puppet.options = ["--pluginsync","--verbose", "--environment dev","--debug"]
        puppet.manifest_file = ""
        puppet.manifests_path = "manifests"
    end

    config.vm.provision "bootstrap", type:"shell", run: "always",  path: "bootstrap.sh"

    config.vm.define "development", primary: true, autostart: true do |development|
        config.vm.network :private_network, ip: "10.100.150.2"

        config.vm.synced_folder(
            "./../",
            "/var/www/furniture.dev",
            nfs: true,
            map_uid: Process.uid,
            map_gid: Process.gid
        )

        development.vm.provider "virtualbox" do |v|
            host = RbConfig::CONFIG['host_os']
            if host =~ /darwin/
                cpus = `sysctl -n hw.ncpu`.to_i
                mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 2
            elsif host =~ /linux/
                cpus = `nproc`.to_i
                mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 2
            else
                cpus = 2
                mem = 4096
            end

            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--memory", mem]
            v.customize ["modifyvm", :id, "--cpus", cpus]

            v.name = "Furniture"
        end
    end

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end
end