services:
    specification.controller.api.specification:
        class: Furniture\SpecificationBundle\Controller\Api\SpecificationController
        arguments:
            - @form.factory
            - @doctrine.orm.default_entity_manager
            - @security.token_storage
            - @pricing.calculator
            - @pricing.twig_extension
            - @security.authorization_checker
            - @validator

    specification.controller.api.specification.sku_item:
        class: Furniture\SpecificationBundle\Controller\Api\SkuSpecificationItemController
        arguments:
            - @form.factory
            - @doctrine.orm.default_entity_manager
            - @security.token_storage
            - @security.authorization_checker
            - @pricing.calculator
            - @pricing.twig_extension
            - @product_pattern.product_variant_creator

    specification.controller.api.specification.custom_item:
        class: Furniture\SpecificationBundle\Controller\Api\CustomSpecificationItemController
        arguments:
            - @form.factory
            - @doctrine.orm.default_entity_manager
            - @security.token_storage
            - @pricing.calculator
            - @pricing.twig_extension
            - @liip_imagine.cache.manager
            - @validator
            - @security.authorization_checker
