specificaiton_api_specification_create:
    path: /create
    methods: [ POST ]
    defaults:
        _controller: specification.controller.api.specification:create

specification_api_specification_editable:
    path: /{specification}/editable
    methods: [ POST ]
    requirements: { specification: \d+ }
    defaults:
        _controller: specification.controller.api.specification:editable

specification_api_specification_info:
    path: /specification/{itemId}/info/{index}
    methods: [ GET ]
    requirements: { itemId: \d+  }
    defaults:
        _controller: specification.controller.api.specification:info

specification_api_specification_item_editable:
    path: /item/{item}/editable
    methods: [ POST ]
    requirements: { item: \d+ }
    defaults:
        _controller: specification.controller.api.specification:editableItem

specification_api_specification_item_remove:
    path: /item/{item}/remove
    methods: GET
    requirements: { item: \d+ }
    defaults:
        _controller: specification.controller.api.specification:remove

specification_api_specification_buyers:
    path: /buyers
    methods: [ GET ]
    defaults:
        _controller: specification.controller.api.specification:buyers
#SKU specification item       
specification_api_specification_sku_item_add:
    path: /catalog/item/add
    methods: [ POST ]
    defaults:
        _controller: specification.controller.api.specification.sku_Item:add

specification_api_specification_sku_item_edit:
    path: /catalog/item/{item}/edit
    methods: [ POST ]
    requirements: { item: \d+ }
    defaults:
        _controller: specification.controller.api.specification.sku_Item:edit
#Custom specification item
specification_api_specification_custom_Item_add:
    path: /custom/item/add
    methods: [ POST ]
    defaults:
        _controller: specification.controller.api.specification.custom_Item:add

specification_api_specification_custom_Item_editable:
    path: /custom/item/{item}/editable
    methods: [ POST ]
    requirements: { item: \d+ }
    defaults:
        _controller: specification.controller.api.specification.custom_Item:editableItem
        
specification_api_specification_custom_Item_info:
    path: /custom/item/{itemId}/info/{index}
    methods: [ GET ]
    requirements: { itemId: \d+  }
    defaults:
        _controller: specification.controller.api.specification.custom_Item:info