services:
    specification.api.request_matcher:
        class: Symfony\Component\HttpFoundation\RequestMatcher
        arguments: [ '/specification/api' ]

    specification.exporter.excel:
        class: Furniture\SpecificationBundle\Exporter\ExcelExporter
        arguments: [ @translator, @pricing.calculator, @liip_imagine.data.manager, @liip_imagine.filter.manager ]

    specification.event_subscriber.modified:
        class: Furniture\SpecificationBundle\EventListener\Doctrine\SpecificationModifiedSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    # Security voters
    security.voter.specification_custom_item:
        class: Furniture\SpecificationBundle\Security\Voter\CustomSpecificationItemVoter
        tags:
            - { name: security.voter }

    security.voter.specification_item:
        class: Furniture\SpecificationBundle\Security\Voter\SpecificationItemVoter
        tags:
            - { name: security.voter }

    security.voter.specification:
        class: Furniture\SpecificationBundle\Security\Voter\SpecificationVoter
        tags:
            - { name: security.voter }

    security.voter.specification_buyer:
        class: Furniture\SpecificationBundle\Security\Voter\BuyerVoter
        tags:
            - { name: security.voter }
