services:
    Furniture.generator.product_variant:
        class: Furniture\ProductBundle\Generator\VariantGenerator
        arguments:
            - '@sylius.repository.product_variant'
            - '@sylius.set_builder.cartesian'
            - '@validator'
            - '@event_dispatcher'
        calls:
        - [setContainer, ['@service_container']]

    Furniture.product.form.ProductVariantPartMaterialsType:
        class: Furniture\ProductBundle\Form\Type\ProductVariantPartMaterialsType
        tags:
            - { name: form.type, alias: ProductVariantPartMaterialsType }
        arguments: 
            em: "@doctrine.orm.entity_manager"

    sylius.validator.variant.combination:
        class: Furniture\ProductBundle\Validator\VariantCombinationValidator
        tags:
            - { name: validator.constraint_validator, alias: sylius.validator.variant.combination }
