parameters:
    sylius.form.type.product_filter.class: Furniture\ProductBundle\Form\Type\ProductFilterType

services:
    furniture.generator.product_variant:
        class: Furniture\ProductBundle\Generator\VariantGenerator
        arguments:
            - '@sylius.repository.product_variant'
            - '@sylius.set_builder.cartesian'
            - '@validator'
            - '@event_dispatcher'
        calls:
        - [setContainer, ['@service_container']]

    furniture.product.form.ProductVariantPartMaterialsType:
        class: Furniture\ProductBundle\Form\Type\ProductVariantPartMaterialsType
        tags:
            - { name: form.type, alias: ProductVariantPartMaterialsType }
        arguments: 
            em: "@doctrine.orm.entity_manager"

    sylius.validator.variant.combination:
        class: Furniture\ProductBundle\Validator\VariantCombinationValidator
        tags:
            - { name: validator.constraint_validator, alias: sylius.validator.variant.combination }

    product_pattern.finder.product_variant:
        class: Furniture\ProductBundle\Pattern\Finder\ProductVariantFinder
        arguments: [ @doctrine.orm.default_entity_manager ]

    product_pattern.product_variant_creator:
        class: Furniture\ProductBundle\Pattern\ProductVariantCreator
        arguments: [ @product_pattern.finder.product_variant, @doctrine.orm.default_entity_manager ]

    product_pattern.product_variant_parameters_validator:
        class: Furniture\ProductBundle\Pattern\ProductVariantParametersValidator
    
    product_pattern.product_variant_price_compiller:
        class: Furniture\ProductBundle\Pattern\ProductVariantPriceCompiller
        arguments: [ @doctrine.orm.default_entity_manager ]

    product.removal_checker:
        class: Furniture\ProductBundle\ProductRemoval\ProductRemovalChecker
        arguments: [ @doctrine.orm.default_entity_manager ]

    product_variant.removal_checker:
        class: Furniture\ProductBundle\ProductRemoval\VariantRemovalChecker
        arguments: [ @doctrine.orm.default_entity_manager ]

    product_attribute.removal_checker:
        class: Furniture\ProductBundle\ProductRemoval\AttributeRemovalChecker
        arguments: [ @doctrine.orm.default_entity_manager ]

    sky_option.removal_checker:
        class: Furniture\ProductBundle\ProductRemoval\SkuOptionTypeRemovalChecker
        arguments: [ @doctrine.orm.default_entity_manager ]

    product_part_material_variant.subscriber.entity:
        class: Furniture\ProductBundle\EventListener\ProductPartMaterialVariantEntitySubscriber
        arguments: [ @sylius.image_uploader, @doctrine.orm.default_entity_manager ]
        tags:
            - { name: kernel.event_subscriber }

    product_variant.doctrine.subscriber.metadata:
        class: Furniture\ProductBundle\EventListener\Doctrine\ProductVariantMetadataSubscriber
        public: false
        tags:
            - { name: doctrine.event_subscriber }

    product_attribute_value.doctrine.subscriber.metadata:
        class: Furniture\ProductBundle\EventListener\Doctrine\ProductAttributeValueMetadataSubscriber
        public: false
        tags:
            - { name: doctrine.event_subscriber }

    twig.extension.product:
        class: Furniture\ProductBundle\Twig\ProductExtension
        arguments: [ @product_variant.removal_checker, @product_attribute.removal_checker, @sky_option.removal_checker ]
        tags:
            - { name: twig.extension }
