# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: migrations.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }

framework:
    translator:      { fallback: %sylius.locale% }
    secret:          %sylius.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%sylius.locale%"
    trusted_proxies: ~
    session:
        handler_id:  ~ # Allow symfony get php provided session handler

sonata_block:
    blocks:
        frontend.block.factories: ~
        frontend.block.products: ~

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions

#Server key!
google_services:
        maps_access_key: AIzaSyB7w4kpPyNfgeUU67t-7FbHtt_1M1YgVK8

twig:
    form:
        resources:
            - CommonBundle:Form:fields.html.twig
            - SyliusWebBundle:Common:forms.html.twig
            - SyliusResourceBundle::forms.html.twig
            - CmfMediaBundle:Form:fields.html.twig
            - SonataFormatterBundle:Form:formatter.html.twig

    debug:            %kernel.debug%
    globals:
        #Browser key
        google_api_maps_key: AIzaSyAtfFR1y2sFVhzLwxvoeX6g_FUofzQakxA
        google_analytics_site_key: '%google.analytics.site%'
    strict_variables: %kernel.debug%
    paths:
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Resources/views: PayumCore
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Stripe/Resources/views: PayumStripe

assetic:
    debug:          %kernel.debug%
    use_controller: %kernel.debug%
    bundles:        ['SyliusWebBundle', 'CmfCreateBundle', 'SyliusResourceBundle', 'FrontendBundle']
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   %sylius.database.driver%
        host:     %sylius.database.host%
        port:     %sylius.database.port%
        dbname:   %sylius.database.name%
        user:     %sylius.database.user%
        password: %sylius.database.password%
        charset:  UTF8

        mapping_types:
            json: json_array

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                dql:
                    string_functions:
                        MATCH: Sylius\Bundle\SearchBundle\Extension\Doctrine\MatchAgainstFunction

doctrine_phpcr:
    session:
        backend: %sylius.phpcr.backend%
        workspace: %sylius.phpcr.workspace%
        username: %sylius.phpcr.user%
        password: %sylius.phpcr.pass%
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

swiftmailer:
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    port:      %sylius.mailer.port%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%

furniture_factory:
    content_access_control:
        roles: [ content_user ]

sylius_core:
    classes:
        product_variant_image:
            model: Furniture\ProductBundle\Entity\ProductVariantImage

sylius_product:
    classes:
        product:
            controller: Furniture\ProductBundle\Controller\ProductController
            model: Furniture\ProductBundle\Entity\Product
            repository: Furniture\ProductBundle\Entity\Repository\ProductRepository
            translation:
                model: Furniture\ProductBundle\Entity\ProductTranslation
                mapping: ~
            form:
                default: Furniture\ProductBundle\Form\Type\ProductType

sylius_attribute:
    classes:
        product:
            attribute:
                model: Sylius\Component\Product\Model\Attribute
                repository: Furniture\ProductBundle\Entity\Repository\AttributeRepository
                translation:
                    model: Sylius\Component\Product\Model\AttributeTranslation
                    mapping: ~

sylius_variation:
    classes:
        product:
            variant:
                controller: Furniture\ProductBundle\Controller\VariantController
                model: Furniture\ProductBundle\Entity\ProductVariant
                repository: Furniture\ProductBundle\Entity\Repository\ProductVariantRepository
                form:
                    default: Furniture\ProductBundle\Form\Type\ProductVariantType

sylius_user:
    classes:
        customer:
            model: Furniture\UserBundle\Entity\Customer
            controller: Furniture\UserBundle\Controller\CustomerController
            repository: Furniture\UserBundle\Entity\Repository\CustomerRepository
            form:
                default: Furniture\UserBundle\Form\Type\CustomerType

        user:
            model: Furniture\UserBundle\Entity\User
            form:
                default: Furniture\UserBundle\Form\Type\UserType
            

sylius_resource:
    resources:
        furniture.factory_user_relation:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\FactoryRetailerRelation
                controller: Furniture\WebBundle\Controller\FactoryRetailerRelationController

        furniture.factories_retialers_relations:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\FactoryRetailerRelation
                repository: Furniture\FactoryBundle\Entity\Repository\FactoryRetailerRelationRepository
                controller: Furniture\WebBundle\Controller\FactoriesRetailersRelationsController

        furniture.retailer_profile:
            driver: doctrine/orm
            classes:
                model: Furniture\RetailerBundle\Entity\RetailerProfile
                repository: Furniture\RetailerBundle\Entity\Repository\RetailerProfileRepository
                translation:
                    model: Furniture\RetailerBundle\Entity\RetailerProfileTranslation
                    mapping: ~

        furniture.factory:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\Factory
                repository: Furniture\FactoryBundle\Entity\Repository\FactoryRepository
                translation:
                    model: Furniture\FactoryBundle\Entity\FactoryTranslation
                    mapping: ~
                    
        furniture.factory_referal_key:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\FactoryReferalKey
                repository: Furniture\FactoryBundle\Entity\Repository\FactoryReferalKeyRepository
                controller: Furniture\WebBundle\Controller\FactoryReferalKeyController
                
        furniture.factory_contact:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\FactoryContact
                translation:
                    model: Furniture\FactoryBundle\Entity\FactoryContactTranslation
                    mapping: ~

        furniture.sku_option:
            driver: doctrine/orm
            classes:
                model: Furniture\SkuOptionBundle\Entity\SkuOptionType
                translation:
                    model: Furniture\SkuOptionBundle\Entity\SkuOptionTypeTranslation
                    mapping: ~

        furniture.product_pattern:
            driver: doctrine/orm
            classes:
                controller: Furniture\ProductBundle\Controller\ProductVariantsPatternController
                model: Furniture\ProductBundle\Entity\ProductVariantsPattern

        furniture.product_pattern_modifier:
            driver: doctrine/orm
            classes:
                controller: Furniture\ProductBundle\Controller\ProductVariantsPatternModifierController
                model: Furniture\ProductBundle\Entity\ProductVariantsPatternModifier

        furniture.product_pdp_intellectual:
            driver: doctrine/orm
            classes:
                controller: Furniture\ProductBundle\Controller\ProductPdpIntellectualController
                model: Furniture\ProductBundle\Entity\PdpIntellectualRoot

        furniture.product_category:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Category
                controller: Furniture\ProductBundle\Controller\CategoryController
                translation:
                    model: Furniture\ProductBundle\Entity\CategoryTranslation
                    mapping: ~

        furniture.product_type:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Type
                controller: Furniture\ProductBundle\Controller\TypeController
                translation:
                    model: Furniture\ProductBundle\Entity\TypeTranslation
                    mapping: ~

        furniture.product_style:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Style
                controller: Furniture\ProductBundle\Controller\StyleController
                translation:
                    model: Furniture\ProductBundle\Entity\StyleTranslation
                    mapping: ~

        furniture.product_space:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Space
                controller: Furniture\ProductBundle\Controller\SpaceController
                translation:
                    model: Furniture\ProductBundle\Entity\SpaceTranslation
                    mapping: ~

        furniture.product_part:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPart
                translation:
                    model: Furniture\ProductBundle\Entity\ProductPartTranslation
                    mapping: ~

        furniture.product_part_type:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartType

        furniture.product_scheme:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductScheme
                translation:
                    model: Furniture\ProductBundle\Entity\ProductSchemeTranslation
                    mapping: ~

        furniture.product_part_material:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartMaterial
                repository: Furniture\ProductBundle\Entity\Repository\ProductPartMaterialRepository
                translation:
                    model: Furniture\ProductBundle\Entity\ProductPartMaterialTranslation
                    mapping: ~

        furniture.product_part_material_option:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartMaterialOption

        furniture.product_part_material_variant_image:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartMaterialVariantImage
                
        furniture.product_part_material_variant:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartMaterialVariant
                controller: Furniture\ProductBundle\Controller\ProductPartMaterialVariantController

        furniture.composite_collection:
            driver: doctrine/orm
            classes:
                model: Furniture\CompositionBundle\Entity\CompositeCollection
                translation:
                    model: Furniture\CompositionBundle\Entity\CompositeCollectionTranslation
                    mapping: ~

        furniture.composite_template:
            driver: doctrine/orm
            classes:
                model: Furniture\CompositionBundle\Entity\CompositeTemplate

        furniture.composite:
            driver: doctrine/orm
            classes:
                model: Furniture\CompositionBundle\Entity\Composite
                translation:
                    model: Furniture\CompositionBundle\Entity\CompositeTranslation
                    mapping: ~

        furniture.specification:
            driver: doctrine/orm
            classes:
                repository: Furniture\SpecificationBundle\Entity\Repository\SpecificationRepository
                controller: Furniture\SpecificationBundle\Controller\SpecificationController
                model: Furniture\SpecificationBundle\Entity\Specification

        furniture.post:
            driver: doctrine/orm
            classes:
                model: Furniture\PostBundle\Entity\Post
                repository: Furniture\PostBundle\Entity\Repository\PostRepository
                translation:
                    model: Furniture\PostBundle\Entity\PostTranslation
                    mapping: ~
    settings:
        default_page_size: 20

liip_imagine:
    filter_sets:
        s200x250:
            filters:
                auto_relative_resize: { widen: 200, heighten: 150 }
                #thumbnail: { size: [200, 150], mode: outbound }
        s201x203:
            filters:
                auto_relative_resize: { widen: 201, heighten: 203 }
                #thumbnail: { size: [201, 203], mode: outbound }

        s150x150:
            filters:
                auto_relative_resize: { widen: 150, heighten: 151 }
                #thumbnail: { size: [150, 150], mode: outbound }

        s150x100:
            filters:
                auto_relative_resize: { widen: 150, heighten: 100 }
                #thumbnail: { size: [150, 100], mode: outbound }

        s425x200:
            filters:
                auto_relative_resize: { widen: 425, heighten: 200 }
                #thumbnail: { size: [425, 200], mode: outbound }

        s100x100:
            filters:
                auto_relative_resize: { widen: 100, heighten: 100 }
                #thumbnail: { size: [100, 100], mode: outbound }

        s160x250:
            filters:
                auto_relative_resize: { widen: 160, heighten: 250 }

        s1170x500:
            filters:
                auto_relative_resize: { widen: 1170, heighten: 500 }
                #thumbnail: { size: [1200, 350], mode: outbound }

        s200x200:
            filters:
                auto_relative_resize: { widen: 200, heighten: 200 }

        s300x225:
            filters:
                auto_relative_resize: { widen: 300, heighten: 225 }
                #thumbnail: { size: [300, 225], mode: outbound }
        s260x195:
            filters:
                auto_relative_resize: { widen: 260, heighten: 195 }
        s360x360:
            filters:
                auto_relative_resize: { widen: 360, heighten: 360 }
                #thumbnail: { size: [360, 360], mode: outbound }
        s570x427:
            filters:
                auto_relative_resize: { widen: 570, heighten: 427 }
