# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: migrations.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }

framework:
    translator:      { fallback: %sylius.locale% }
    secret:          %sylius.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%sylius.locale%"
    trusted_proxies: ~
    session:
        handler_id: session.handler.native

sonata_block:
    blocks:
        frontend.block.factories: ~
        frontend.block.products: ~

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions

#Server key!
google_services:
        maps_access_key: AIzaSyB7w4kpPyNfgeUU67t-7FbHtt_1M1YgVK8

twig:
    form:
        resources:
            - CommonBundle:Form:fields.html.twig
            - SyliusWebBundle:Common:forms.html.twig
            - SyliusResourceBundle::forms.html.twig
            - CmfMediaBundle:Form:fields.html.twig
            - SonataFormatterBundle:Form:formatter.html.twig

    debug:            %kernel.debug%
    globals:
        #Browser key
        google_api_maps_key: AIzaSyAtfFR1y2sFVhzLwxvoeX6g_FUofzQakxA
    strict_variables: %kernel.debug%
    paths:
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Resources/views: PayumCore
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Stripe/Resources/views: PayumStripe

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['SyliusWebBundle', 'CmfCreateBundle', 'SyliusResourceBundle', 'FrontendBundle']
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   %sylius.database.driver%
        host:     %sylius.database.host%
        port:     %sylius.database.port%
        dbname:   %sylius.database.name%
        user:     %sylius.database.user%
        password: %sylius.database.password%
        charset:  UTF8

        mapping_types:
            json: json_array

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                dql:
                    string_functions:
                        MATCH: Sylius\Bundle\SearchBundle\Extension\Doctrine\MatchAgainstFunction

doctrine_phpcr:
    session:
        backend: %sylius.phpcr.backend%
        workspace: %sylius.phpcr.workspace%
        username: %sylius.phpcr.user%
        password: %sylius.phpcr.pass%
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

swiftmailer:
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    port:      %sylius.mailer.port%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%

furniture_factory:
    content_access_control:
        roles: [ content_user ]

sylius_product:
    classes:
        product:
            controller: Furniture\ProductBundle\Controller\ProductController
            model: Furniture\ProductBundle\Entity\Product
            repository: Furniture\ProductBundle\Entity\Repository\ProductRepository
            form:
                default: Furniture\ProductBundle\Form\Type\ProductType

sylius_variation:
    classes:
        product:
            variant:
                controller: Furniture\ProductBundle\Controller\VariantController
                model: Furniture\ProductBundle\Entity\ProductVariant
                repository: Furniture\ProductBundle\Entity\Repository\ProductVariantRepository
                form:
                    default: Furniture\ProductBundle\Form\Type\ProductVariantType

sylius_user:
    classes:
        customer:
            model: Sylius\Component\Core\Model\Customer
            controller: Furniture\CommonBundle\Controller\CustomerController
            repository: Furniture\CommonBundle\Entity\Repository\CustomerRepository
            form:
                default: Furniture\CommonBundle\Form\Type\CustomerType

        user:
            model: Furniture\CommonBundle\Entity\User
            form:
                default: Furniture\CommonBundle\Form\Type\UserType
            

sylius_resource:
    resources:
        furniture.factory_user_relation:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\FactoryRetailerRelation
                controller: Furniture\WebBundle\Controller\FactoryRetailerRelationController

        furniture.retailer_profile:
            driver: doctrine/orm
            classes:
                model: Furniture\RetailerBundle\Entity\RetailerProfile

        furniture.factory:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\Factory
                translation:
                    #repository: Furniture\FactoryBundle\Entity\Repository\FactoryRepository
                    model: Furniture\FactoryBundle\Entity\FactoryTranslation
                    mapping: ~

        furniture.factory_contact:
            driver: doctrine/orm
            classes:
                model: Furniture\FactoryBundle\Entity\FactoryContact
                translation:
                    model: Furniture\FactoryBundle\Entity\FactoryContactTranslation
                    mapping: ~

        furniture.sku_option:
            driver: doctrine/orm
            classes:
                model: Furniture\SkuOptionBundle\Entity\SkuOptionType
                translation:
                    model: Furniture\SkuOptionBundle\Entity\SkuOptionTypeTranslation
                    mapping: ~

        furniture.product_category:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Category
                translation:
                    model: Furniture\ProductBundle\Entity\CategoryTranslation
                    mapping: ~

        furniture.product_type:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Type
                translation:
                    model: Furniture\ProductBundle\Entity\TypeTranslation
                    mapping: ~

        furniture.product_style:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Style
                translation:
                    model: Furniture\ProductBundle\Entity\StyleTranslation
                    mapping: ~

        furniture.product_space:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Space
                translation:
                    model: Furniture\ProductBundle\Entity\SpaceTranslation
                    mapping: ~

        furniture.product_readiness:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\Readiness

        furniture.product_part:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPart
                translation:
                    model: Furniture\ProductBundle\Entity\ProductPartTranslation
                    mapping: ~

        furniture.product_part_type:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartType

        furniture.product_part_material:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartMaterial
                translation:
                    model: Furniture\ProductBundle\Entity\ProductPartMaterialTranslation
                    mapping: ~

        furniture.product_part_material_option:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartMaterialOption

        furniture.product_part_material_variant:
            driver: doctrine/orm
            classes:
                model: Furniture\ProductBundle\Entity\ProductPartMaterialVariant
                controller: Furniture\ProductBundle\Controller\ProductPartMaterialVariantController

        furniture.composite_collection:
            driver: doctrine/orm
            classes:
                model: Furniture\CompositionBundle\Entity\CompositeCollection
                translation:
                    model: Furniture\CompositionBundle\Entity\CompositeCollectionTranslation
                    mapping: ~

        furniture.composite_template:
            driver: doctrine/orm
            classes:
                model: Furniture\CompositionBundle\Entity\CompositeTemplate

        furniture.composite:
            driver: doctrine/orm
            classes:
                model: Furniture\CompositionBundle\Entity\Composite
                translation:
                    model: Furniture\CompositionBundle\Entity\CompositeTranslation
                    mapping: ~

        furniture.specification:
            driver: doctrine/orm
            classes:
                model: Furniture\SpecificationBundle\Entity\Specification

        furniture.post:
            driver: doctrine/orm
            classes:
                model: Furniture\PostBundle\Entity\Post
                translation:
                    model: Furniture\PostBundle\Entity\PostTranslation
                    mapping: ~

liip_imagine:
    filter_sets:
        s200x250:
            filters:
                thumbnail: { size: [200, 150], mode: outbound }
        s201x203:
            filters:
                thumbnail: { size: [201, 203], mode: outbound }

        s150x150:
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
        s425x200:
            filters:
                thumbnail: { size: [425, 200], mode: outbound }

        s100x100:
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

        s1200x350:
            filters:
                thumbnail: { size: [1200, 350], mode: outbound }

        s200x200:
            filters:
                auto_relative_resize: { widen: 200, heighten: 200 }
        s300x225:
            filters:
                thumbnail: { size: [300, 225], mode: outbound }
        s360x360:
            filters:
                thumbnail: { size: [360, 360], mode: outbound }