doctrine_migrations:
    dir_name:             '%kernel.root_dir%/DoctrineMigrations'
    namespace:            Furniture\Migrations
    table_name:           migration_versions
    name:                 'Furniture Migrations'