furniture_factory:
    resource: "@FurnitureFactoryBundle/Resources/config/routing.yml"
    prefix:   /

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"
    
create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

specification:
    resource: "@SpecificationBundle/Resources/config/routing.yml"

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
