# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        sylius_user_provider:
            id: sylius.user_provider.name_or_email

    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    firewalls:
        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     sylius_user_provider
                login_path:   /administration/login
                check_path:   /administration/login-check
                failure_path: /administration/login
                default_target_path: /administration/dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   /logout
                target: /administration/login
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*
            form_login:
                provider: sylius_user_provider
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                    amazon:   "/login/check-amazon"
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                login_path:   /login
                failure_path: /login
                oauth_user_provider:
                    service: sylius.oauth.user_provider
            logout:
                path: /logout

            anonymous: true

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_ADMINISTRATION_ACCESS }

        - { path: "/account.*", role: ROLE_USER }
        - { path: ^/api, role: ROLE_API }
        - { path: "/_partial.*", ip: 127.0.0.1 }

        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.+, role: ROLE_USER }

sylius_rbac:
    permissions:
        furniture.manage.sku_options: manage sku attributes
        Furniture.sku_option.index: list sku attributes
        Furniture.sku_option.create: create new sku attribute
        Furniture.sku_option.update: update sku attribute
        Furniture.sku_option.delete: delete sku attribute

        furniture.manage.product_part_materials: manage product part materials
        furniture.product_part_material.index: list product part materials
        furniture.product_part_material.create: create product part material
        furniture.product_part_material.update: update product part material
        furniture.product_part_material.delete: delete product part material
        furniture.product_part_material.show: show product part material

        furniture.manage.product_part_material_types: manage product part material types
        furniture.product_part_type.index: list product part type
        furniture.product_part_type.create: create product part type
        furniture.product_part_type.update: update product part type
        furniture.product_part_type.delete: delete product part type
        
        furniture.manage.product_part_material_options: manage product part material options
        furniture.product_part_material_option.index: list product part material options
        furniture.product_part_material_option.create: create product part material option
        furniture.product_part_material_option.update: update product part materialfurniture.product_part_type.index option
        furniture.product_part_material_option.delete: delete product part material option

        furniture.manage.product_part_material_variants: manage product part material variants
        furniture.product_part_material_variant.index: list product part material variants
        furniture.product_part_material_variant.create: create a product part material variant
        furniture.product_part_material_variant.update: update product part material variant
        furniture.product_part_material_variant.delete: delete product part material variant
        furniture.product_part_material_variant.generate: generate a product part material variants
        
        furniture.manage.factories: manage factories
        Furniture.factory.show: show details page
        Furniture.factory.index: show factories manage page
        Furniture.factory.create: edit factory data
        Furniture.factory.update: update factory data
        Furniture.factory.delete: delete factory data
        
        furniture.manage.factories.user_relations: manage factory user relations
        Furniture.factory_user_relation.index: users list
        Furniture.factory_user_relation.show: show detail page
        Furniture.factory_user_relation.create: create new relation
        Furniture.factory_user_relation.update: update current relation
        Furniture.factory_user_relation.delete: delete relation

        furniture.manage.composite_collections: manage composite collection
        furniture.composite_collection.index: list composite collections
        furniture.composite_collection.create: create a composite collection
        furniture.composite_collection.update: update a composite collection
        furniture.composite_collection.delete: delete a composite collection

        furniture.manage.composite_templates: manage composite templates
        furniture.composite_template.index: list composite templates
        furniture.composite_template.create: create a composite template
        furniture.composite_template.update: update a composite template
        furniture.composite_template.delete: delete a composite template

        furniture.manage.composite: manage composities
        furniture.composite.index: list composities
        furniture.composite.create: create composite
        furniture.composite.update: update compose
        furniture.composite.delete: delete composite

        furniture.manage.specifications: manage specifications
        furniture.specification.index: list specifications
        furniture.specification.show: show specification
        furniture.specification.delete: delete specifications

        sylius.product.variantGrouEdit: variants group update
    permissions_hierarchy:
        furniture.manage.factories:
            - Furniture.factory.show
            - Furniture.factory.index
            - Furniture.factory.create
            - Furniture.factory.update
            - Furniture.factory.delete
            
        furniture.manage.factories.user_relations:
            - Furniture.factory_user_relation.show
            - Furniture.factory_user_relation.index
            - Furniture.factory_user_relation.create
            - Furniture.factory_user_relation.update
            - Furniture.factory_user_relation.delete
        
        furniture.manage.sku_options: 
            - Furniture.sku_option.index
            - Furniture.sku_option.create
            - Furniture.sku_option.update
            - Furniture.sku_option.delete
            - sylius.product.variantGrouEdit

        furniture.manage.product_part_materials:
            - furniture.product_part_material.index
            - furniture.product_part_material.create
            - furniture.product_part_material.update
            - furniture.product_part_material.delete
            - furniture.product_part_material.show

        furniture.manage.product_part_material_types:
            - furniture.product_part_type.index
            - furniture.product_part_type.create
            - furniture.product_part_type.update
            - furniture.product_part_type.delete

        furniture.manage.product_part_material_options:
            - furniture.product_part_material_option.index
            - furniture.product_part_material_option.create
            - furniture.product_part_material_option.update
            - furniture.product_part_material_option.delete

        furniture.manage.product_part_material_variants:
            - furniture.product_part_material_variant.index
            - furniture.product_part_material_variant.create
            - furniture.product_part_material_variant.update
            - furniture.product_part_material_variant.delete
            - furniture.product_part_material_variant.generate

        furniture.manage.composite_collections:
            - furniture.composite_collection.index
            - furniture.composite_collection.create
            - furniture.composite_collection.update
            - furniture.composite_collection.delete

        furniture.manage.composite_templates:
            - furniture.composite_template.index
            - furniture.composite_template.create
            - furniture.composite_template.update
            - furniture.composite_template.delete

        furniture.manage.composite:
            - furniture.composite.index
            - furniture.composite.create
            - furniture.composite.update
            - furniture.composite.delete

        furniture.manage.specifications:
            - furniture.specification.index
            - furniture.specification.show
            - furniture.specification.delete

    security_roles:
        ROLE_CONTENT_USER: It's our Architect/Designer/Retailer, factory user such as factory manager or agent
        ROLE_FACTORY_ADMIN: It's our Factory administer
        ROLE_FACTORY_USER: It's out Factory user
        
    roles:
        content_user:
            name: User
            description: Architect/Designer/Retailer
            permissions: []
            security_roles: [ ROLE_CONTENT_USER ]

        factory_admin:
            name: Factory admin
            description: Factory administer
            permissions: []
            security_roles: [ ROLE_FACTORY_ADMIN ]

        factory_user:
            name: Factory user
            description: Factory user
            permissions: []
            security_roles: [ ROLE_FACTORY_USER ]

        administrator:
            name: Administrator
            description: Administrator user
            permissions:
                - furniture.manage.composite
                - furniture.manage.composite_templates
                - furniture.manage.composite_collections
                - furniture.manage.product_part_material_types
                - furniture.manage.product_part_materials
                - furniture.manage.product_part_material_options
                - furniture.manage.product_part_material_variants
                - furniture.manage.sku_options
                - furniture.manage.factories
                - furniture.manage.factories.user_relations
                - furniture.manage.specifications

            security_roles: [ ROLE_ADMINISTRATION_ACCESS ]
