# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        sylius_user_provider:
            id: sylius.user_provider.name_or_email

    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern:  ^/(css|images|js|media)/
            security: false
        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     sylius_user_provider
                login_path:   /administration/login
                check_path:   /administration/login-check
                failure_path: /administration/login
                default_target_path: /administration/dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   /administration/logout
                target: /administration/login
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*
            form_login:
                provider: sylius_user_provider
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout:
                path: /logout

            anonymous: true

    access_control:
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/need-reset-password.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/verify-email.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_ADMINISTRATION_ACCESS }

        - { path: "/account.*", role: ROLE_USER }
        - { path: ^/api, role: ROLE_API }
        - { path: "/_partial.*", ip: 127.0.0.1 }

        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.+, role: ROLE_USER }

sylius_rbac:
    permissions:
        furniture.manage.sku_options: manage sku attributes
        furniture.sku_option.index: list sku attributes
        furniture.sku_option.create: create new sku attribute
        furniture.sku_option.update: update sku attribute
        furniture.sku_option.delete: delete sku attribute

        furniture.manage.product_patterns: manage product patterns
        furniture.product_pattern.index: list product patterns
        furniture.product_pattern.create: create new product pattern
        furniture.product_pattern.update: update product pattern
        furniture.product_pattern.delete: delete product pattern

        furniture.manage.product_pattern_modifiers: manage product pattern modifiers
        furniture.product_pattern_modifier.index: list product pattern modifiers
        furniture.product_pattern_modifier.create: create new product pattern modifier
        furniture.product_pattern_modifier.update: update product pattern modifier
        furniture.product_pattern_modifier.delete: delete product pattern modifier

        furniture.manage.product_categories: manage product categories
        furniture.product_category.index: list product categories
        furniture.product_category.create: create product category
        furniture.product_category.update: update product category
        furniture.product_category.delete: delete product category

        furniture.manage.product_types: manage product types
        furniture.product_type.index: list product types
        furniture.product_type.create: create product type
        furniture.product_type.update: update product type
        furniture.product_type.delete: delete product type

        furniture.manage.product_styles: manage product styles
        furniture.product_style.index: list product styles
        furniture.product_style.create: create product style
        furniture.product_style.update: update product style
        furniture.product_style.delete: delete product style

        furniture.manage.product_spaces: manage product spaces
        furniture.product_space.index: list product spaces
        furniture.product_space.create: create product space
        furniture.product_space.update: update product space
        furniture.product_space.delete: delete product space

        furniture.manage.product_readiness: manage product readiness
        furniture.product_readiness.index: list product readiness
        furniture.product_readiness.create: create product readiness
        furniture.product_readiness.update: update product readiness
        furniture.product_readiness.delete: delete product readiness

        furniture.manage.product_part_materials: manage product part materials
        furniture.product_part_material.index: list product part materials
        furniture.product_part_material.create: create product part material
        furniture.product_part_material.update: update product part material
        furniture.product_part_material.delete: delete product part material
        furniture.product_part_material.show: show product part material

        furniture.manage.product_part_material_types: manage product part material types
        furniture.product_part_type.index: list product part type
        furniture.product_part_type.create: create product part type
        furniture.product_part_type.update: update product part type
        furniture.product_part_type.delete: delete product part type
        
        furniture.manage.product_part_material_options: manage product part material options
        furniture.product_part_material_option.index: list product part material options
        furniture.product_part_material_option.create: create product part material option
        furniture.product_part_material_option.update: update product part materialfurniture.product_part_type.index option
        furniture.product_part_material_option.delete: delete product part material option

        furniture.manage.product_part_material_variants: manage product part material variants
        furniture.product_part_material_variant.index: list product part material variants
        furniture.product_part_material_variant.create: create a product part material variant
        furniture.product_part_material_variant.update: update product part material variant
        furniture.product_part_material_variant.delete: delete product part material variant
        furniture.product_part_material_variant.generate: generate a product part material variants

        furniture.manage.product_pdp_intellectual: manage pdp intelectuals
        furniture.product_pdp_intellectual.index: list pdp intellectuals
        furniture.product_pdp_intellectual.create: create pdp intellectual
        furniture.product_pdp_intellectual.update: update pdp intellectual
        furniture.product_pdp_intellectual.delete: delete pdp intellectual
        
        furniture.manage.factories: manage factories
        furniture.factory.show: show details page
        furniture.factory.index: show factories manage page
        furniture.factory.create: edit factory data
        furniture.factory.update: update factory data
        furniture.factory.delete: delete factory data
        
        furniture.manage.retailer_profile: manage retailer profiles
        furniture.retailer_profile.index: show retailers profiles
        furniture.retailer_profile.create: create new retailer profile
        furniture.retailer_profile.update: update retailer profile
        furniture.retailer_profile.delete: delete retailer profile
        
        furniture.manage.factories.user_relations: manage factory user relations
        furniture.factory_user_relation.index: users list
        furniture.factory_user_relation.show: show detail page
        furniture.factory_user_relation.create: create new relation
        furniture.factory_user_relation.update: update current relation
        furniture.factory_user_relation.delete: delete relation

        furniture.manage.composite_collections: manage composite collection
        furniture.composite_collection.index: list composite collections
        furniture.composite_collection.create: create a composite collection
        furniture.composite_collection.update: update a composite collection
        furniture.composite_collection.delete: delete a composite collection

        furniture.manage.composite_templates: manage composite templates
        furniture.composite_template.index: list composite templates
        furniture.composite_template.create: create a composite template
        furniture.composite_template.update: update a composite template
        furniture.composite_template.delete: delete a composite template

        furniture.manage.composite: manage composities
        furniture.composite.index: list composities
        furniture.composite.create: create composite
        furniture.composite.update: update compose
        furniture.composite.delete: delete composite

        furniture.manage.specifications: manage specifications
        furniture.specification.index: list specifications
        furniture.specification.show: show specification
        furniture.specification.delete: delete specifications

        furniture.manage.posts: manage posts
        furniture.post.index: list posts
        furniture.post.show: show post
        furniture.post.create: create post
        furniture.post.update: update post
        furniture.post.delete: delete post

        sylius.product.variantGrouEdit: variants group update
    permissions_hierarchy:
        furniture.manage.factories:
            - furniture.factory.show
            - furniture.factory.index
            - furniture.factory.create
            - furniture.factory.update
            - furniture.factory.delete
            
        furniture.manage.retailer_profile:
            - furniture.retailer_profile.index
            - furniture.retailer_profile.create
            - furniture.retailer_profile.update
            - furniture.retailer_profile.delete
            
        furniture.manage.factories.user_relations:
            - furniture.factory_user_relation.show
            - furniture.factory_user_relation.index
            - furniture.factory_user_relation.create
            - furniture.factory_user_relation.update
            - furniture.factory_user_relation.delete
        
        furniture.manage.sku_options: 
            - furniture.sku_option.index
            - furniture.sku_option.create
            - furniture.sku_option.update
            - furniture.sku_option.delete
            - sylius.product.variantGrouEdit

        furniture.manage.product_patterns:
            - furniture.product_pattern.index
            - furniture.product_pattern.create
            - furniture.product_pattern.update
            - furniture.product_pattern.delete

        furniture.manage.product_pattern_modifiers:
            - furniture.product_pattern_modifier.index
            - furniture.product_pattern_modifier.create
            - furniture.product_pattern_modifier.update
            - furniture.product_pattern_modifier.delete

        furniture.manage.product_pdp_intellectual:
            - furniture.product_pdp_intellectual.index
            - furniture.product_pdp_intellectual.create
            - furniture.product_pdp_intellectual.update
            - furniture.product_pdp_intellectual.delete

        furniture.manage.product_categories:
            - furniture.product_category.index
            - furniture.product_category.create
            - furniture.product_category.update
            - furniture.product_category.delete

        furniture.manage.product_types:
            - furniture.product_type.index
            - furniture.product_type.create
            - furniture.product_type.update
            - furniture.product_type.delete

        furniture.manage.product_styles:
            - furniture.product_style.index
            - furniture.product_style.create
            - furniture.product_style.update
            - furniture.product_style.delete

        furniture.manage.product_spaces:
            - furniture.product_space.index
            - furniture.product_space.create
            - furniture.product_space.update
            - furniture.product_space.delete

        furniture.manage.product_readiness:
            - furniture.product_readiness.index
            - furniture.product_readiness.create
            - furniture.product_readiness.update
            - furniture.product_readiness.delete

        furniture.manage.product_part_materials:
            - furniture.product_part_material.index
            - furniture.product_part_material.create
            - furniture.product_part_material.update
            - furniture.product_part_material.delete
            - furniture.product_part_material.show

        furniture.manage.product_part_material_types:
            - furniture.product_part_type.index
            - furniture.product_part_type.create
            - furniture.product_part_type.update
            - furniture.product_part_type.delete

        furniture.manage.product_part_material_options:
            - furniture.product_part_material_option.index
            - furniture.product_part_material_option.create
            - furniture.product_part_material_option.update
            - furniture.product_part_material_option.delete

        furniture.manage.product_part_material_variants:
            - furniture.product_part_material_variant.index
            - furniture.product_part_material_variant.create
            - furniture.product_part_material_variant.update
            - furniture.product_part_material_variant.delete
            - furniture.product_part_material_variant.generate

        furniture.manage.composite_collections:
            - furniture.composite_collection.index
            - furniture.composite_collection.create
            - furniture.composite_collection.update
            - furniture.composite_collection.delete

        furniture.manage.composite_templates:
            - furniture.composite_template.index
            - furniture.composite_template.create
            - furniture.composite_template.update
            - furniture.composite_template.delete

        furniture.manage.composite:
            - furniture.composite.index
            - furniture.composite.create
            - furniture.composite.update
            - furniture.composite.delete

        furniture.manage.specifications:
            - furniture.specification.index
            - furniture.specification.show
            - furniture.specification.delete

        furniture.manage.posts:
            - furniture.post.show
            - furniture.post.create
            - furniture.post.index
            - furniture.post.update
            - furniture.post.delete

    security_roles:
        ROLE_CONTENT_USER: It's our Architect/Designer/Retailer, factory user such as factory manager or agent
        ROLE_FACTORY_ADMIN: It's our Factory administer
        ROLE_FACTORY_USER: It's out Factory user
        
    roles:
        content_user:
            name: User
            description: Architect/Designer/Retailer
            permissions: []
            security_roles: [ ROLE_CONTENT_USER ]

        factory_admin:
            name: Factory admin
            description: Factory administer
            permissions: []
            security_roles: [ ROLE_FACTORY_ADMIN ]

        factory_user:
            name: Factory user
            description: Factory user
            permissions: []
            security_roles: [ ROLE_FACTORY_USER ]

        administrator:
            name: Administrator
            description: Administrator user
            permissions:
                - furniture.manage.composite
                - furniture.manage.composite_templates
                - furniture.manage.composite_collections
                - furniture.manage.product_part_material_types
                - furniture.manage.product_part_materials
                - furniture.manage.product_part_material_options
                - furniture.manage.product_part_material_variants
                - furniture.manage.sku_options
                - furniture.manage.product_patterns
                - furniture.manage.product_pattern_modifiers
                - furniture.manage.product_pdp_intellectual
                - furniture.manage.product_categories
                - furniture.manage.product_types
                - furniture.manage.product_styles
                - furniture.manage.product_spaces
                - furniture.manage.product_readiness
                - furniture.manage.factories
                - furniture.manage.factories.user_relations
                - furniture.manage.specifications
                - furniture.manage.posts
                - furniture.manage.retailer_profile

            security_roles: [ ROLE_ADMINISTRATION_ACCESS ]
