# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        sylius_user_provider:
            id: sylius.user_provider.name_or_email

    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    firewalls:
        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     sylius_user_provider
                login_path:   /administration/login
                check_path:   /administration/login-check
                failure_path: /administration/login
                default_target_path: /administration/dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   /logout
                target: /administration/login
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*
            form_login:
                provider: sylius_user_provider
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                    amazon:   "/login/check-amazon"
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                login_path:   /login
                failure_path: /login
                oauth_user_provider:
                    service: sylius.oauth.user_provider
            logout: true
            anonymous: true

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_ADMINISTRATION_ACCESS }

        - { path: "/account.*", role: ROLE_USER }

        - { path: ^/api, role: ROLE_API }

        - { path: "/_partial.*", ip: 127.0.0.1 }

sylius_rbac:
    permissions:
        furniture.manage.sku_options: manage sku attributes
        Furniture.sku_option.index: list sku attributes
        Furniture.sku_option.create: create new sku attribute
        Furniture.sku_option.update: update sku attribute
        Furniture.sku_option.delete: delete sku attribute

        furniture.manage.product_extensions: manage product extensions
        furniture.product_extension.index: list product extensions
        furniture.product_extension.create: create product extension
        furniture.product_extension.update: update product extension
        furniture.product_extension.delete: delete product extension
        furniture.product_extension.show: show product extension

        furniture.manage.product_extension_options: manage product extension options
        furniture.product_extension_option.index: list product extension options
        furniture.product_extension_option.create: create product extension option
        furniture.product_extension_option.update: update product extension option
        furniture.product_extension_option.delete: delete product extension option

        furniture.manage.product_extension_variants: manage product extension variants
        furniture.product_extension_variant.index: list product extension variants
        furniture.product_extension_variant.create: create a product extension variant
        furniture.product_extension_variant.update: update product extension variant
        furniture.product_extension_variant.delete: delete product extension variant
        furniture.product_extension_variant.generate: generate a product extension variants

        furniture.manage.composite_collections: manage composite collection
        furniture.composite_collection.index: list composite collections
        furniture.composite_collection.create: create a composite collection
        furniture.composite_collection.update: update a composite collection
        furniture.composite_collection.delete: delete a composite collection

        furniture.manage.composite_templates: manage composite templates
        furniture.composite_template.index: list composite templates
        furniture.composite_template.create: create a composite template
        furniture.composite_template.update: update a composite template
        furniture.composite_template.delete: delete a composite template

        furniture.manage.composite: manage composities
        furniture.composite.index: list composities
        furniture.composite.create: create composite
        furniture.composite.update: update compose
        furniture.composite.delete: delete composite

    permissions_hierarchy:
        furniture.manage.sku_options: 
            - Furniture.sku_option.index
            - Furniture.sku_option.create
            - Furniture.sku_option.update
            - Furniture.sku_option.delete

        furniture.manage.product_extensions:
            - furniture.product_extension.index
            - furniture.product_extension.create
            - furniture.product_extension.update
            - furniture.product_extension.delete
            - furniture.product_extension.show

        furniture.manage.product_extension_options:
            - furniture.product_extension_option.index
            - furniture.product_extension_option.create
            - furniture.product_extension_option.update
            - furniture.product_extension_option.delete

        furniture.manage.product_extension_variants:
            - furniture.product_extension_variant.index
            - furniture.product_extension_variant.create
            - furniture.product_extension_variant.update
            - furniture.product_extension_variant.delete
            - furniture.product_extension_variant.generate

        furniture.manage.composite_collections:
            - furniture.composite_collection.index
            - furniture.composite_collection.create
            - furniture.composite_collection.update
            - furniture.composite_collection.delete

        furniture.manage.composite_templates:
            - furniture.composite_template.index
            - furniture.composite_template.create
            - furniture.composite_template.update
            - furniture.composite_template.delete

        furniture.manage.composite:
            - furniture.composite.index
            - furniture.composite.create
            - furniture.composite.update
            - furniture.composite.delete

    roles:
        administrator:
            name: Administrator
            description: Administrator user
            permissions:
                - furniture.manage.composite
                - furniture.manage.composite_templates
                - furniture.manage.composite_collections
                - furniture.manage.product_extensions
                - furniture.manage.product_extension_options
                - furniture.manage.product_extension_variants
                - furniture.manage.sku_options

            security_roles: [ ROLE_ADMINISTRATION_ACCESS ]
