services:
    frontend.block.factories:
        class: Furniture\FrontendBundle\Blocks\FactoriesBlock
        arguments: [ @frontend.repository.factory, @templating ]
        tags:
            - { name: sonata.block }

    frontend.block.products:
        class: Furniture\FrontendBundle\Blocks\ProductsBlock
        arguments: [ @frontend.repository.product, @templating ]
        tags:
            - { name: sonata.block }

    frontend.block.best_sellers:
        class: Furniture\FrontendBundle\Blocks\ProductsBestSellersBlock
        arguments: [ '@doctrine.orm.default_entity_manager', '@templating' ]
        tags:
            - { name: sonata.block }