services:
    frontend.controller.homepage:
        class: Furniture\FrontendBundle\Controller\HomepageController
        arguments: [ @twig, @router, %available_locales% ]

    frontend.controller.catalog:
        class: Furniture\FrontendBundle\Controller\CatalogController
        arguments:
            - @twig
            - @frontend.repository.product
            - @frontend.repository.factory
            - @sylius.repository.taxon
            - @sylius.repository.taxonomy
            - @frontend.repository.specification
            - @frontend.repository.specification_item
            - @security.token_storage

    frontend.controller.product:
        class: Furniture\FrontendBundle\Controller\ProductController
        arguments:
            - @twig
            - @frontend.repository.product
            - @sylius.repository.taxon
            - @frontend.repository.specification
            - @frontend.repository.specification_item
            - @security.token_storage

    frontend.controller.security:
        class: Furniture\FrontendBundle\Controller\SecurityController
        arguments: [ @twig, @security.csrf.token_manager ]

    frontend.controller.specification:
        class: Furniture\FrontendBundle\Controller\SpecificationController
        arguments:
            - @twig
            - @frontend.repository.specification
            - @security.token_storage
            - @form.factory
            - @doctrine.orm.default_entity_manager
            - @router
            - @specification.exporter.excel

    frontend.controller.specification_buyer:
        class: Furniture\FrontendBundle\Controller\SpecificationBuyerController
        arguments:
            - @twig
            - @frontend.repository.specification_buyer
            - @security.token_storage
            - @form.factory
            - @doctrine.orm.default_entity_manager
            - @router

    # Factory profile controllers
    frontend.controller.factory.dashboard:
        class: Furniture\FrontendBundle\Controller\Profile\Factory\DashboardController
        arguments:
            - @twig
            - @sylius.authorization_checker

    frontend.controller.factory.user_relation:
        class: Furniture\FrontendBundle\Controller\Profile\Factory\UserRelationController
        arguments:
            - @twig
            - @frontend.repository.factory_user_relation
            - @doctrine.orm.default_entity_manager
            - @security.token_storage
            - @router
            - @form.factory

    frontend.controller.factory.default_relation:
        class: Furniture\FrontendBundle\Controller\Profile\Factory\DefaultRelationController
        arguments:
            - @twig
            - @doctrine.orm.default_entity_manager
            - @security.token_storage
            - @router
            - @form.factory
            
    frontend.controller.factory.user_map:
        class: Furniture\FrontendBundle\Controller\Profile\Factory\UserMapController
        arguments:
            - @twig
            - @doctrine.orm.default_entity_manager
            - @security.token_storage

    # Content user profile controllers
    frontend.controller.content_user.dashboard:
        class: Furniture\FrontendBundle\Controller\Profile\ContentUser\DashboardController
        arguments:
            - @twig
            - @security.token_storage

    frontend.controller.content_user.factory_rates:
        class: Furniture\FrontendBundle\Controller\Profile\ContentUser\FactoryRatesController
        arguments:
            - @twig
            - @security.token_storage
            - @frontend.repository.user_factory_rate
            - @doctrine.orm.default_entity_manager
            - @form.factory
            - @router

    frontend.controller.content_user.factory_relation:
        class: Furniture\FrontendBundle\Controller\Profile\ContentUser\FactoryRelationController
        arguments:
            - @twig
            - @frontend.repository.factory_user_relation
            - @doctrine.orm.default_entity_manager
            - @security.token_storage
            - @router
            - @form.factory

    frontend.controller.factory_section:
        class: Furniture\FrontendBundle\Controller\FactoryController
        arguments:
            - @twig
            - @frontend.repository.factory
            - @frontend.repository.post
            - @security.token_storage