services:
    form.type.retailer_employee:
        class: Furniture\FrontendBundle\Form\Type\RetailerEmployee\RetailerEmployeeType
        arguments: [ @security.token_storage ]
        tags:
            - { name: form.type, alias: retailer_employee }

    form.type.retailer_factory_relations:
        class: Furniture\FrontendBundle\Form\Type\FactoryRetailerRelationType
        arguments: [ @frontend.repository.factory_retailer_relation, @frontend.repository.factory, @security.token_storage ]
        tags:
            - { name: form.type, alias: retailer_factory_relation }

    form.type.retailer_employee_customer:
        class: Furniture\FrontendBundle\Form\Type\RetailerEmployee\RetailerEmployeeCustomerType
        arguments: [ @doctrine.orm.default_entity_manager ]
        tags:
            - { name: form.type, alias: retailer_employee_customer }

    form.type.retailer_factory_rate:
        class: Furniture\FrontendBundle\Form\Type\RetailerFactoryRateType
        arguments: [ @frontend.repository.factory, @security.token_storage ]
        tags:
            - { name: form.type, alias: retailer_factory_rate }
