services:
    frontend.menu_builder:
        class: Furniture\FrontendBundle\Menu\FrontendMenuBuilder
        arguments:
            - @knp_menu.factory
            - @translator
            - @security.authorization_checker
            - @sylius.authorization_checker
            - @router
            - @security.token_storage
            - @frontend.repository.product_space
            - @request_stack

    frontend.menu.retailer.header:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createReatilerHeaderMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.header.retailer }

    frontend.menu.factory.header:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createFactoryHeaderMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.header.factory }

    frontend.menu.profile.header:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createProfileHeaderMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.header.profile }

    frontend.menu.footer:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createFooterMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.footer }

    frontend.menu.factory_profile:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createFactoryProfileMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.factory_profile }

    frontend.menu.retailer_admin_profile:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createRetailerAdminProfileMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.retailer_admin_profile }
            
    frontend.menu.factory_side:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createFactorySideMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.factory_side }
            
    frontend.menu.user_profile:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createUserProfileMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.user_profile }