services:
    frontend.menu_builder:
        class: Furniture\FrontendBundle\Menu\FrontendMenuBuilder
        arguments:
            - @knp_menu.factory
            - @translator
            - @security.authorization_checker
            - @sylius.authorization_checker
            - @router
            - @security.token_storage

    frontend.menu.header:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createHeaderMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.header }

    frontend.menu.footer:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createFooterMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.footer }

    frontend.menu.factory_profile:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createFactoryProfileMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.factory_profile }

    frontend.menu.content_user_profile:
        class: Knp\Menu\MenuItem
        factory_service: frontend.menu_builder
        factory_method: createContentUserProfileMenu
        tags:
            - { name: knp_menu.menu, alias: frontend.content_user_profile }