services:
    frontend.repository.factory:
        class: Furniture\FrontendBundle\Repository\FactoryRepository
        arguments:
            - @doctrine.orm.default_entity_manager
            - 'Furniture\FactoryBundle\Entity\Factory'

    frontend.repository.product:
        class: Furniture\FrontendBundle\Repository\ProductRepository
        arguments:
            - @doctrine.orm.default_entity_manager
            - 'Furniture\ProductBundle\Entity\Product'

    frontend.repository.specification:
        class: Furniture\FrontendBundle\Repository\SpecificationRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.specification_buyer:
        class: Furniture\FrontendBundle\Repository\SpecificationBuyerRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.specification_item:
        class: Furniture\FrontendBundle\Repository\SpecificationItemRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.user_factory_rate:
        class: Furniture\FrontendBundle\Repository\UserFactoryRateRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.factory_user_relation:
        class: Furniture\FrontendBundle\Repository\FactoryUserRelationRepository
        arguments: [ @doctrine.orm.default_entity_manager ]
