services:
    frontend.repository.factory:
        class: Furniture\FrontendBundle\Repository\FactoryRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.product:
        class: Furniture\FrontendBundle\Repository\ProductRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.specification:
        class: Furniture\FrontendBundle\Repository\SpecificationRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.specification_buyer:
        class: Furniture\FrontendBundle\Repository\SpecificationBuyerRepository
        arguments: [ @doctrine.orm.default_entity_manager ]