services:
    frontend.repository.factory:
        class: Furniture\FrontendBundle\Repository\FactoryRepository
        arguments:
            - @doctrine.orm.default_entity_manager
            - 'Furniture\FactoryBundle\Entity\Factory'

    frontend.repository.product:
        class: Furniture\FrontendBundle\Repository\ProductRepository
        arguments:
            - @doctrine.orm.default_entity_manager
            - 'Furniture\ProductBundle\Entity\Product'

    frontend.repository.product_category:
        class: Furniture\FrontendBundle\Repository\ProductCategoryRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.product_space:
        class: Furniture\FrontendBundle\Repository\ProductSpaceRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.product_type:
        class: Furniture\FrontendBundle\Repository\ProductTypeRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.product_style:
        class: Furniture\FrontendBundle\Repository\ProductStyleRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.specification:
        class: Furniture\FrontendBundle\Repository\SpecificationRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.specification_buyer:
        class: Furniture\FrontendBundle\Repository\SpecificationBuyerRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.specification_item:
        class: Furniture\FrontendBundle\Repository\SpecificationItemRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.retailer_factory_rate:
        class: Furniture\FrontendBundle\Repository\RetailerFactoryRateRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.factory_retailer_relation:
        class: Furniture\FrontendBundle\Repository\FactoryRetailerRelationRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.post:
        class: Furniture\FrontendBundle\Repository\PostRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.composite_collection:
        class: Furniture\FrontendBundle\Repository\CompositeCollectionRepository
        arguments: [ @doctrine.orm.default_entity_manager ]

    frontend.repository.retailer_employee:
        class: Furniture\FrontendBundle\Repository\RetailerEmployeeRepository
        arguments: [ @doctrine.orm.default_entity_manager ]
        
    frontend.repository.retailer_profile:
        class: Furniture\FrontendBundle\Repository\RetailerProfileRepository
        arguments: [ @doctrine.orm.default_entity_manager ]
