homepage_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.homepage:index

homepage:
    path: /{_locale}/
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.homepage:home

catalog:
    path: /{_locale}/catalog
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.catalog:catalog
        
products:
    path: /{_locale}/products
    methods: [ GET ]
    requirements: 
        _locale: %available_locales%
    defaults:
        _controller: frontend.controller.catalog:products

product:
    path: /{_locale}/product/{product}
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.product:product

# Specifications
specificaitons:
    prefix: /{_locale}/specifications
    resource: '@FrontendBundle/Resources/config/routing/specifications.yml'

# Specification buyers
specificaiton_buyers:
    prefix: /{_locale}/clients
    resource: '@FrontendBundle/Resources/config/routing/clients.yml'

# Factory routes
factory:
    resource: '@FrontendBundle/Resources/config/routing/factory.yml'
    prefix: /{_locale}/factory/room

# Factory profile
factory_profile:
    resource: '@FrontendBundle/Resources/config/routing/factory_profile.yml'
    prefix: /{_locale}/profile/factory

# Factory site side
factory_side:
    resource: '@FrontendBundle/Resources/config/routing/factory_side.yml'
    prefix: /{_locale}/factory

# Content user profile
retailer_profile:
    resource: '@FrontendBundle/Resources/config/routing/retailer_profile.yml'
    prefix: /{_locale}/profile/retailer
    
# Content user profile
user_profile:
    resource: '@FrontendBundle/Resources/config/routing/user_profile.yml'
    prefix: /{_locale}/profile/user

# Security
_security:
    resource: '@FrontendBundle/Resources/config/routing/security.yml'
    prefix: /
