homepage_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.homepage:index

homepage:
    path: /{_locale}/
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.homepage:home

product:
    path: /{_locale}/product/{product}
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.product:product
