homepage_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.homepage:index

homepage:
    path: /{_locale}/
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.homepage:home

product:
    path: /{_locale}/product/{product}
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.product:product
        
catalog:
    path: /{_locale}/catalog
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.catalog:catalog
        
products:
    path: /{_locale}/products
    methods: [ GET ]
    requirements: 
        _locale: %available_locales%
    defaults:
        _controller: frontend.controller.catalog:products

# Specifications
specifications:
    path: /{_locale}/specifications
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.specification:specifications

specification_create:
    path: /{_locale}/specifications/new
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.specification:edit

specification_edit:
    path: /{_locale}/specifications/{specification}/edit
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales%, specification: \d+ }
    defaults:
        _controller: frontend.controller.specification:edit

specification_remove:
    path: /{_locale}/specifications/{specification}/remove
    methods: [ GET ]
    requirements: { _locale: %available_locales%, specification: \d+ }
    defaults:
        _controller: frontend.controller.specification:remove

specification_finish:
    path: /{_locale}/specifications/{specification}/finish
    methods: [ GET ]
    requirements: { _locale: %available_locales%, specification: \d+ }
    defaults:
        _controller: frontend.controller.specification:finish

specification_export_preview:
    path: /{_locale}/specifications/{specification}/export/preview
    methods: [ GET ]
    requirements: { _locale: %available_locales%, specification: \d+ }
    defaults:
        _controller: frontend.controller.specification:exportPreview

specification_export:
    path: /{_locale}/specifications/{specification}/export
    methods: [ GET ]
    requirements: { _locale: %available_locales%, specification: \d+ }
    defaults:
        _controller: frontend.controller.specification:export

# Specification buyers
specificaiton_buyers:
    prefix: /{_locale}/clients
    resource: @FrontendBundle/Resources/config/routing/clients.yml

# Factory routes
factory:
    resource: @FrontendBundle/Resources/config/routing/factory.yml
    prefix: /{_locale}/factory/room

# Factory profile
factory_profile:
    resource: @FrontendBundle/Resources/config/routing/factory_profile.yml
    prefix: /{_locale}/profile/factory

# Factory site side
factory_side:
    resource: @FrontendBundle/Resources/config/routing/factory_side.yml
    prefix: /{_locale}/factory

# Content user profile
retailer_profile:
    resource: @FrontendBundle/Resources/config/routing/retailer_profile.yml
    prefix: /{_locale}/profile/retailer
    
# Content user profile
user_profile:
    resource: @FrontendBundle/Resources/config/routing/user_profile.yml
    prefix: /{_locale}/profile/user

# Security
security_login:
    path: /login
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:login

security_login_check:
    path: /login_check

security_logout:
    path: /logout
