services:
    twig.extension.frontend:
        class: Furniture\FrontendBundle\Twig\FrontendExtension
        arguments: [ @knp_menu.helper, @frontend.menu_builder ]
        tags:
            - { name: twig.extension }

    form.type.furniture_retailer_profile_frontend:
            class: Furniture\FrontendBundle\Form\Type\RetailerProfileType
            arguments: [ '@google_service.maps.geocoding' ]
            tags:
                - { name: form.type, alias: furniture_retailer_profile_frontend }
