services:
    furniture_factory.factory_entity_listener:
        class: Furniture\FactoryBundle\EventListener\FactoryEntityListener
        calls:
            - [ setContainer, ['@service_container'] ]
        tags:
            - { name: kernel.event_listener, event: Furniture.factory.pre_create, method: pre_create }
            - { name: kernel.event_listener, event: Furniture.factory.pre_update, method: pre_update }

    factory.security.voter.view_price:
        class: Furniture\FactoryBundle\Security\Voter\ViewPriceVoter
        tags:
            - { name: security.voter }

    factory.security.voter.view_products:
        class: Furniture\FactoryBundle\Security\Voter\ViewProductsVoter
        tags:
            - { name: security.voter }

    factory.security.voter.view_factory:
        class: Furniture\FactoryBundle\Security\Voter\ViewFactoryVoter
        tags:
            - { name: security.voter }

    factory.security.voter.factory_retailer_relation:
        class: Furniture\FactoryBundle\Security\Voter\FactoryRetailerRelationVoter
        tags:
            - { name: security.voter }

    factory.removal_checker:
        class: Furniture\FactoryBundle\FactoryRemoval\FactoryRemovalChecker
        arguments: [ @doctrine.orm.default_entity_manager ]

    twig.extension.factory:
        class: Furniture\FactoryBundle\Twig\FactoryExtension
        arguments: [ @factory.removal_checker ]
        tags:
            - { name: twig.extension }
