Furniture\CommonBundle\Entity\User:
    type: entity
    table: furniture_user
    
    oneToMany:
        factoryRelations:
            cascade: [persist]
            orphanRemoval: true
            targetEntity: Furniture\FactoryBundle\Entity\FactoryUserRelation
            mappedBy: user

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            inversedBy: users
            joinColumn:
                name: factory_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL