Furniture\CommonBundle\Entity\User:
    type: entity
    table: furniture_user

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            inversedBy: users
            cascade: [ persist ]
            joinColumn:
                name: factory_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL

    oneToOne:
        retailerUserProfile:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerUserProfile
            mappedBy: user
            cascade: [ persist ]