Furniture\FactoryBundle\Entity\Factory:
    type: entity
    table: factory
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            name: created_at

    oneToMany:
        userRelations:
            cascade: [persist]
            orphanRemoval: true
            targetEntity: Furniture\FactoryBundle\Entity\FactoryUserRelation
            mappedBy: factory

        images:
            cascade: [persist]
            orphanRemoval: true
            targetEntity: Furniture\FactoryBundle\Entity\FactoryImage
            mappedBy: factory

        products:
            cascade: [persist]
            orphanRemoval: true
            targetEntity: Furniture\ProductBundle\Entity\Product
            fetch: EXTRA_LAZY
            mappedBy: factory
