Furniture\FactoryBundle\Entity\FactoryTranslation:
    type: entity
    inheritanceType: SINGLE_TABLE
    table: factory_translation
    id:
        id:
             type: integer
             nullable: false
             unsigned: false
             id: true
             generator:
                 strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
        shortDescription:
            type: text
            nullable: true
