Furniture\FactoryBundle\Entity\Factory:
    type: entity
    table: factory
    repositoryClass: Furniture\FactoryBundle\Entity\Repository\FactoryRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            nullable: true

        createdAt:
            type: datetime
            nullable: true
            name: created_at

        enabled:
            type: boolean
            nullable: false
            options:
                default: false

    oneToMany:
        retailerRelations:
            cascade: [persist]
            orphanRemoval: true
            targetEntity: Furniture\FactoryBundle\Entity\FactoryRetailerRelation
            mappedBy: factory
            fetch: EXTRA_LAZY

        images:
            cascade: [persist]
            orphanRemoval: true
            targetEntity: Furniture\FactoryBundle\Entity\FactoryImage
            mappedBy: factory

        products:
            cascade: [persist]
            orphanRemoval: true
            targetEntity: Furniture\ProductBundle\Entity\Product
            fetch: EXTRA_LAZY
            mappedBy: factory

        users:
            targetEntity: Furniture\UserBundle\Entity\User
            mappedBy: factory

        contacts:
            targetEntity: Furniture\FactoryBundle\Entity\FactoryContact
            cascade: [ persist ]
            orphanRemoval: true
            mappedBy: factory

    oneToOne:
        defaultRelation:
            targetEntity: Furniture\FactoryBundle\Entity\FactoryDefaultRelation
            mappedBy: factory
            cascade: [ persist ]

        logoImage:
            targetEntity: Furniture\FactoryBundle\Entity\FactoryLogoImage
            mappedBy: factory
            cascade: [ persist ]
