Furniture\FactoryBundle\Entity\FactoryTranslation:
    type: entity
    inheritanceType: SINGLE_TABLE
    table: factory_translation
    id:
        id:
            name: id
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true

        shortDescription:
            type: text
            nullable: true

        address:
            type: string
            nullable: true

        workInfoContent:
            type: text
            nullable: true
            name: work_info_content

        collectionContent:
            type: text
            nullable: true
            name: collection_content
