Furniture\FactoryBundle\Entity\UserFactoryRate:
    type: entity
    table: user_factory_rates
    repositoryClass: Furniture\FactoryBundle\Entity\Repository\UserFactoryRateRepository

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            joinColumn:
                name: factory_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

        user:
            targetEntity: Furniture\CommonBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

    fields:
        coefficient:
            name: coefficient
            type: float

        dumping:
            name: dumping
            type: float