Furniture\RetailerBundle\Entity\RetailerProfile:
    type: entity
    table: furniture_retailer_profile
    repositoryClass: Furniture\RetailerBundle\Entity\Repository\RetailerProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    oneToMany:
        retailerUserProfiles:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerUserProfile
            mappedBy: retailerProfile
            cascade: [ persist ]
         
    oneToOne:
        logoImage:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerProfileLogoImage
            mappedBy: retailerProfile
            cascade: [ persist ]

    manyToMany:
        demoFactories:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            joinTable:
                name: retailer_profile_demo_factories
                joinColumns:
                    profile_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE

                inverseJoinColumns:
                    factory_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
            
    fields:
        name:
            type: string
            nullable: true
            
        website:
            type: string
            nullable: true
            
        subtitle:
            type: string
            nullable: true
            
        description:
            type: text
            nullable: true

        phones:
            type: json_array
            name: phones

        emails:
            type: json_array
            name: emails
            
        lat:
            type: float
            name: latitude
            nullable: true
            
        lng:
            type: float
            name: longtitude
            nullable: true
            
        country:
            type: string
            name: Country
            nullable: true
            
        locality:
            type: string
            name: City
            nullable: true
            
        streetNumber:
            type: string
            name: Street number
            nullable: true
            
        route:
            type: string
            name: Street number
            nullable: true
        
        sublocalityLevel1:
            type: string
            nullable: true
            
        sublocalityLevel2:
            type: string
            nullable: true
            
        sublocalityLevel3:
            type: string
            nullable: true
            
        sublocalityLevel4:
            type: string
            nullable: true
            
        sublocalityLevel5:
            type: string
            nullable: true
            
        administrativeAreaLevel1:
            type: string
            nullable: true
            
        administrativeAreaLevel2:
            type: string
            nullable: true
            
        administrativeAreaLevel3:
            type: string
            nullable: true
            
        administrativeAreaLevel4:
            type: string
            nullable: true
            
        administrativeAreaLevel5:
            type: string
            nullable: true
            
        createdAt:
            type: datetime
            name: created_at
            nullable: true

        updatedAt:
            type: datetime
            name: updated_at
            nullable: true
            
    lifecycleCallbacks:
        preUpdate: [ onUpdate ]