Furniture\RetailerBundle\Entity\RetailerUserProfile:
    type: entity
    table: retailer_user_profile
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            
    fields:
        retailerMode:
            type: smallint
            name: retailer_mode
            nullable: true

        position:
            type: string
            name: position
            nullable: true

        phones:
            type: json_array
            name: phones

        emails:
            type: json_array
            name: emails
                
    oneToOne:
        user:
            targetEntity: Furniture\UserBundle\Entity\User
            inversedBy: retailerUserProfile
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false
            
    manyToOne:
        retailerProfile:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerProfile
            inversedBy: retailerUserProfiles
            cascade: [ persist ]
            joinColumn:
                name: retailer_profile_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL