Furniture\RetailerBundle\Entity\RetailerProfileLogoImage:
    type: entity
    table: retailer_profile_logo_image
    
    oneToOne:
        retailerProfile:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerProfile
            inversedBy: logoImage
            joinColumn:
                name: retailer_profile_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false
        