Furniture\RetailerBundle\Entity\RetailerProfile:
    type: entity
    table: furniture_retailer_profile
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    oneToMany:
        retailerUserProfiles:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerUserProfile
            mappedBy: retailerProfile
            cascade: [ persist ]
         
    oneToOne:
        logoImage:
            targetEntity: Furniture\RetailerBundle\Entity\RetailerProfileLogoImage
            mappedBy: retailerProfile
            cascade: [ persist ]
            
    fields:
        name:
            type: string
            nullable: true
            
        website:
            type: string
            nullable: true
            
        subtitle:
            type: string
            nullable: true
            
        description:
            type: text
            nullable: true
            
        address:
            type: string
            name: address
            nullable: true

        phones:
            type: json_array
            name: phones

        emails:
            type: json_array
            name: emails