Furniture\ProductBundle\Entity\Category:
    type: entity
    table: product_category
    repositoryClass: Furniture\ProductBundle\Entity\Repository\CategoryRepository

    id:
        id:
            name: id
            type: integer
            generator:
                strategy: AUTO

    fields:
        slug:
            type: string
            name: slug

        position:
            type: integer
            name: position

    manyToOne:
        parent:
            targetEntity: Furniture\ProductBundle\Entity\Category
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE

    oneToMany:
        children:
            targetEntity: Furniture\ProductBundle\Entity\Category
            mappedBy: parent

    uniqueConstraints:
        product_category_slug_unique:
            columns: [ slug ]