Furniture\ProductBundle\Entity\PdpIntellectualRoot:
    type: entity
    table: product_pdp_intellectual_root

    id:
        id:
            column: id
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            column: name
            
        graphJson:
            type: json_array
            column: graph_json
            
        treeJson:
            type: json_array
            column: graph_tree_json
            nullable: true
        
        treePathForInputsJson:
            type: json_array
            column: tree_path_for_input_json
            nullable: true

    oneToOne:
        expression:
            targetEntity: Furniture\ProductBundle\Entity\PdpIntellectualCompositeExpression
            cascade: [ persist, remove ]
            joinColumn:
                name: expression_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

    manyToOne:
        product:
            targetEntity: Furniture\ProductBundle\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
