Furniture\ProductBundle\Entity\ProductExtensionOption:
    type: entity
    table: product_extension_option

    id:
        id:
            type: integer
            id: true
            name: id
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            name: name