Furniture\ProductBundle\Entity\Product:
    type: entity
    table: furniture_product

    oneToMany:
        skuOptionVariants:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
            cascade: [persist]
            mappedBy: product
            orphanRemoval: true
            OrderBy:
            skuOptionType: ASC

        productParts:
            targetEntity: ProductPart
            cascade: [persist]
            mappedBy: product
            orphanRemoval: true

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            inversedBy: products
            joinColumn:
                name: factory_id
                referencedColumnName: id
                onDelete: "SET NULL"
                nullable: true

    manyToMany:
        subProducts:
            targetEntity: Product
            cascade: [persist]
            inversedBy: bundleProducts
            joinTable:
                name: bundle_products_relation
                joinColumns:
                    bundle_product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    child_product_id:
                        referencedColumnName: id
        bundleProducts:
            fetch: EXTRA_LAZY
            targetEntity: Product
            mappedBy: subProducts

        compositeCollections:
            targetEntity: Furniture\CompositionBundle\Entity\CompositeCollection
            orphanRemoval: true
            joinTable:
                name: product_composite_collection_relation
                joinColumns:
                    product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    composite_collection_id:
                        referencedColumnName: id

    oneToOne:
        pdpConfig:
            targetEntity: Furniture\ProductBundle\Entity\ProductPdpConfig
            mappedBy: product
            cascade: [ persist ]

    indexes:
        factoryCode_index:
            columns:
                - factoryCode
    fields:
        factoryCode:
            type: string
            nullable: true