Furniture\ProductBundle\Entity\ProductPartVariantSelection:
    type: entity
    table: furniture_product_part_variant_selection
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    manyToOne:
        productPart:
            targetEntity: Furniture\ProductBundle\Entity\ProductPart
            joinColumn:
                cascade: [ persist ]
                name: product_part_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

        productVariant:
            targetEntity: Furniture\ProductBundle\Entity\ProductVariant
            inversedBy: productPartVariantSelections
            joinColumn:
                cascade: [ persist ]
                name: product_variant_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

        productPartMaterialVariant:
            targetEntity: Furniture\ProductBundle\Entity\ProductPartMaterialVariant
            joinColumn:
                cascade: [ persist ]
                name: product_part_material_variant_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE