Furniture\ProductBundle\Entity\Product:
    type: entity
    table: furniture_product

    oneToMany:
        productSchemes:
            targetEntity: Furniture\ProductBundle\Entity\ProductScheme
            cascade: [persist]
            mappedBy: product
            orphanRemoval: true
            OrderBy:
                id: ASC
        skuOptionVariants:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
            cascade: [persist]
            mappedBy: product
            orphanRemoval: true
            OrderBy:
            skuOptionType: ASC

        productParts:
            targetEntity: ProductPart
            cascade: [persist]
            mappedBy: product
            orphanRemoval: true

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            inversedBy: products
            joinColumn:
                name: factory_id
                referencedColumnName: id
                onDelete: "SET NULL"
                nullable: true

    manyToMany:
        subProducts:
            targetEntity: Product
            cascade: [persist]
            inversedBy: bundleProducts
            joinTable:
                name: bundle_products_relation
                joinColumns:
                    bundle_product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    child_product_id:
                        referencedColumnName: id
        bundleProducts:
            fetch: EXTRA_LAZY
            targetEntity: Product
            mappedBy: subProducts

        compositeCollections:
            targetEntity: Furniture\CompositionBundle\Entity\CompositeCollection
            orphanRemoval: true
            joinTable:
                name: product_composite_collection_relation
                joinColumns:
                    product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    composite_collection_id:
                        referencedColumnName: id

        categories:
            targetEntity: Furniture\ProductBundle\Entity\Category
            joinTable:
                name: product_categories
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
                        onDelete: CASCADE

        spaces:
            targetEntity: Furniture\ProductBundle\Entity\Space
            joinTable:
                name: product_spaces
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    space_id:
                        referencedColumnName: id
                        onDelete: CASCADE

        types:
            targetEntity: Furniture\ProductBundle\Entity\Type
            joinTable:
                name: product_types
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    type_id:
                        referencedColumnName: id
                        onDelete: CASCADE

        styles:
            targetEntity: Furniture\ProductBundle\Entity\Style
            joinTable:
                name: product_styles
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    style_id:
                        referencedColumnName: id
                        onDelete: CASCADE

        readinesses:
            targetEntity: Furniture\ProductBundle\Entity\Readiness
            joinTable:
                name: product_readiness_relation
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    readiness_id:
                        referencedColumnName: id
                        onDelete: CASCADE

    oneToOne:
        pdpConfig:
            targetEntity: Furniture\ProductBundle\Entity\ProductPdpConfig
            mappedBy: product
            cascade: [ persist ]

    indexes:
        factoryCode_index:
            columns:
                - factoryCode
    fields:
        factoryCode:
            type: string
            nullable: true
        availableForSale:
            type: boolean
            nullable: true