Furniture\ProductBundle\Entity\ProductVariantsPatternModifier:
    type: entity
    table: product_variants_pattern_modifier

    id:
        id:
            type: integer
            column: id
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            column: name

        price:
            type: string
            column: price

        attach:
            type: smallint
            column: attach

        position:
            type: integer
            column: position

    manyToOne:
        scheme:
            targetEntity: Furniture\ProductBundle\Entity\ProductScheme
            joinColumn:
                name: scheme_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE

        product:
            targetEntity: Furniture\ProductBundle\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

        pattern:
            targetEntity: Furniture\ProductBundle\Entity\ProductVariantsPattern
            joinColumn:
                name: pattern_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE

    oneToMany:
        partPatternVariantSelections:
            targetEntity: Furniture\ProductBundle\Entity\ProductPartPatternVariantModifierSelection
            mappedBy: pattern
            cascade: [ persist ]
            orphanRemoval: true

    manyToMany:
        skuOptionValues:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
            joinTable:
                name: product_variants_modifier_sku_option_variants
                joinColumns:
                    pattern_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    sku_option_variant_id:
                        referencedColumnName: id
                        onDelete: CASCADE
