Furniture\ProductBundle\Entity\ProductTranslation:
    type: entity
    table: product_translation

    attributeOverride:
        description:
            column: description
            type: text
            nullable: true
    fields:
        searchTsv:
            type: tsvector
            column: search_tsv
            default: ''
            options:
                searchOptions:
                    searchFields: [name, description]
