Furniture\ProductBundle\Entity\ProductVariant:
    type: entity
    inheritanceType: SINGLE_TABLE
    
    manyToMany:
        skuOptions:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
            onDelete: CASCADE
            joinTable:
                name: variant_sku_options_relation
                joinColumns:
                    product_variant_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    sku_option_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"

        extensionVariants:
            targetEntity: Furniture\ProductBundle\Entity\ProductExtensionVariant
            orphanRemoval: true
            joinTable:
                name: product_variant_extension_variant_relation
                joinColumns:
                    product_variant_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    product_extension_variant_id:
                        referencedColumnName: id
