Furniture\ProductBundle\Entity\ProductVariant:
    type: entity
    table: product_variant

    oneToMany:
        productPartVariantSelections:
            orphanRemoval: true
            cascade: [ persist ]
            targetEntity: ProductPartVariantSelection
            mappedBy: productVariant
    
    manyToMany:
        skuOptions:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
            cascade: [ persist ]
            onDelete: CASCADE
            joinTable:
                name: variant_sku_options_relation
                joinColumns:
                    product_variant_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    sku_option_id:
                        referencedColumnName: id
                        onDelete: CASCADE

#        extensionVariants:
#            targetEntity: Furniture\ProductBundle\Entity\ProductExtensionVariant
#            orphanRemoval: true
#            joinTable:
#                name: product_variant_extension_variant_relation
#                joinColumns:
#                    product_variant_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    product_extension_variant_id:
#                        referencedColumnName: id
