Furniture\ProductBundle\Entity\Product:
    type: entity
    table: furniture_product
    oneToMany:
        skuOptionVariants:
          targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
          cascade: [persist]
          mappedBy: product
          orphanRemoval: true
          OrderBy:
            - skuOptionType: ASC

    manyToMany:
        subProducts:
            targetEntity: Product
            cascade: [persist]
            joinTable:
                name: bundle_products_relation

                joinColumns:
                    bundle_product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    child_product_id:
                        referencedColumnName: id
        bundleProducts:
            fetch: EXTRA_LAZY
            targetEntity: Product
            mappedBy: subProducts

        extensionVariants:
            targetEntity: Furniture\ProductBundle\Entity\ProductExtensionVariant
            orphanRemoval: true
            joinTable:
                name: product_extension_variant_relation
                joinColumns:
                    product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    product_extension_variant_id:
                        referencedColumnName: id

    indexes:
        factoryCode_index:
            columns:
                - factoryCode
    fields:
        factoryCode:
            type: string
            nullable: true