Furniture\ProductBundle\Entity\ProductExtensionOptionValue:
    type: entity
    table: product_extension_option_value

    id:
        id:
            type: integer
            name: id
            id: true
            generator:
                strategy: AUTO

    fields:
        value:
            type: string
            name: value

    manyToOne:
        extension:
            targetEntity: Furniture\ProductBundle\Entity\ProductExtension
            inversedBy: optionValues
            joinColumn:
                name: product_extension_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

        option:
            targetEntity: Furniture\ProductBundle\Entity\ProductExtensionOption
            joinColumn:
                name: product_extension_option_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
