Furniture\ProductBundle\Entity\ProductPartMaterialOptionValue:
    type: entity
    table: product_part_material_option_value

    id:
        id:
            type: integer
            name: id
            id: true
            generator:
                strategy: AUTO

    fields:
        value:
            type: string
            name: value

    manyToOne:
        material:
            targetEntity: Furniture\ProductBundle\Entity\ProductPartMaterial
            inversedBy: optionValues
            joinColumn:
                name: product_extension_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

        option:
            targetEntity: Furniture\ProductBundle\Entity\ProductPartMaterialOption
            joinColumn:
                name: product_extension_option_id
                referencedColumnName: id
                nullable: false
                onDelete: RESTRICT
