Furniture\ProductBundle\Entity\Product:
    type: entity
    table: furniture_product
    oneToMany:
        skuOptionVariants:
          targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
          cascade: [persist]
          mappedBy: product
          orphanRemoval: true
          OrderBy:
            - skuOptionType: ASCZA
        productParts:
            targetEntity: ProductPart
            cascade: [persist]
            mappedBy: product
            orphanRemoval: true

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            inversedBy: products
            joinColumn:
                name: product_id
                referencedColumnName: id
                onDelete: "SET NULL"
                nullable: true

    manyToMany:
        subProducts:
            targetEntity: Product
            cascade: [persist]
            inversedBy: bundleProducts
            joinTable:
                name: bundle_products_relation
                joinColumns:
                    bundle_product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    child_product_id:
                        referencedColumnName: id
        bundleProducts:
            fetch: EXTRA_LAZY
            targetEntity: Product
            mappedBy: subProducts

#        extensions:
#            targetEntity: Furniture\ProductBundle\Entity\ProductExtension
#            orphanRemoval: true
#            joinTable:
#                name: product_extension_relation
#                joinColumns:
#                    product_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    product_extension_id:
#                        referencedColumnName: id

        compositeCollections:
            targetEntity: Furniture\CompositionBundle\Entity\CompositeCollection
            orphanRemoval: true
            joinTable:
                name: product_composite_collection_relation
                joinColumns:
                    product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    composite_collection_id:
                        referencedColumnName: id

    indexes:
        factoryCode_index:
            columns:
                - factoryCode
    fields:
        factoryCode:
            type: string
            nullable: true