Furniture\ProductBundle\Entity\ProductPdpInput:
    type: entity
    table: product_pdp_input

    id:
        id:
            name: id
            type: integer
            generator:
                strategy: AUTO

    fields:
        position:
            type: integer
            name: position
        type:
            type: integer
            name: type
            options:
                default: 0

    manyToOne:
        config:
            targetEntity: Furniture\ProductBundle\Entity\ProductPdpConfig
            inversedBy: inputs
            joinColumn:
                name: config_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE

        option:
            targetEntity: Sylius\Component\Product\Model\Option
            joinColumn:
                name: option_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE

        skuOption:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionType
            joinColumn:
                name: sku_option_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE

        productPart:
            targetEntity: Furniture\ProductBundle\Entity\ProductPart
            joinColumn:
                name: product_part_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE

    uniqueConstraints:
        product_pdp_input_unique:
            columns: [ config_id, option_id, sku_option_id, product_part_id ]
