Furniture\ProductBundle\Entity\ProductExtensionTranslation:
    type: entity
    table: product_extension_translation

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        presentation:
            type: string
            nullable: true

