Furniture\ProductBundle\Entity\Product:
    type: entity
    table: product

    oneToMany:
        productSchemes:
            targetEntity: Furniture\ProductBundle\Entity\ProductScheme
            cascade: [ persist ]
            mappedBy: product
            orphanRemoval: true
            orderBy:
                id: ASC

        productVariantsPatterns:
            targetEntity: Furniture\ProductBundle\Entity\ProductVariantsPattern
            cascade: [ persist ]
            mappedBy: product
            orphanRemoval: true
            orderBy:
                id: ASC

        skuOptionVariants:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
            cascade: [ persist ]
            mappedBy: product
            orphanRemoval: true
            orderBy:
                skuOptionType: ASC

        productParts:
            targetEntity: Furniture\ProductBundle\Entity\ProductPart
            cascade: [ persist ]
            mappedBy: product
            orphanRemoval: true

    manyToOne:
        factory:
            targetEntity: Furniture\FactoryBundle\Entity\Factory
            inversedBy: products
            joinColumn:
                name: factory_id
                referencedColumnName: id
                onDelete: RESTRICT
                nullable: true

    manyToMany:
        subProducts:
            targetEntity: Product
            cascade: [ persist ]
            inversedBy: bundleProducts
            joinTable:
                name: bundle_products_relation
                joinColumns:
                    bundle_product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    child_product_id:
                        referencedColumnName: id

        bundleProducts:
            fetch: EXTRA_LAZY
            targetEntity: Product
            mappedBy: subProducts

        compositeCollections:
            targetEntity: Furniture\CompositionBundle\Entity\CompositeCollection
            orphanRemoval: true
            joinTable:
                name: product_composite_collection_relation
                joinColumns:
                    product_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    composite_collection_id:
                        referencedColumnName: id

        categories:
            targetEntity: Furniture\ProductBundle\Entity\Category
            joinTable:
                name: product_categories
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
                        onDelete: RESTRICT

        spaces:
            targetEntity: Furniture\ProductBundle\Entity\Space
            joinTable:
                name: product_spaces
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    space_id:
                        referencedColumnName: id
                        onDelete: RESTRICT

        types:
            targetEntity: Furniture\ProductBundle\Entity\Type
            joinTable:
                name: product_types
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    type_id:
                        referencedColumnName: id
                        onDelete: RESTRICT

        styles:
            targetEntity: Furniture\ProductBundle\Entity\Style
            joinTable:
                name: product_styles
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE

                inverseJoinColumns:
                    style_id:
                        referencedColumnName: id
                        onDelete: RESTRICT

    oneToOne:
        pdpConfig:
            targetEntity: Furniture\ProductBundle\Entity\ProductPdpConfig
            mappedBy: product
            cascade: [ persist ]

    indexes:
        factoryCode_index:
            columns:
                - factory_code

    fields:
        factoryCode:
            type: string
            nullable: true
            column: factory_code

        availableForSale:
            type: boolean
            nullable: true
            column: available_for_sale

        productType:
            type: smallint
            column: product_type
