Furniture\ProductBundle\Entity\ProductPartMaterial:
    type: entity
    table: product_part_material

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            name: name

    oneToMany:
        optionValues:
            targetEntity: Furniture\ProductBundle\Entity\ProductPartMaterialOptionValue
            mappedBy: material
            cascade: [ persist ]
            orphanRemoval: true

        variants:
            targetEntity: Furniture\ProductBundle\Entity\ProductPartMaterialVariant
            mappedBy: material
            cascade: [ persist ]
            orphanRemoval: true
