Furniture\ProductBundle\Entity\ProductVariant:
    type: entity
    table: product_variant

    oneToMany:
        productPartVariantSelections:
            orphanRemoval: true
            cascade: [ persist ]
            targetEntity: Furniture\ProductBundle\Entity\ProductPartVariantSelection
            mappedBy: productVariant
    
    manyToOne:
        productScheme:
            targetEntity: Furniture\ProductBundle\Entity\ProductScheme
            inversedBy: productVariants
            joinColumn:
                name: product_scheme_id
                referencedColumnName: id
                onDelete: cascade
                nullable: true
    
    manyToMany:
        skuOptions:
            targetEntity: Furniture\SkuOptionBundle\Entity\SkuOptionVariant
            cascade: [ persist ]
            onDelete: CASCADE
            joinTable:
                name: variant_sku_options_relation
                joinColumns:
                    product_variant_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    sku_option_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                        
    fields:
        factoryCode:
            type: string
            nullable: true
            column: factory_code
