Furniture\ProductBundle\Entity\Style:
    type: entity
    table: product_style
    repositoryClass: Furniture\ProductBundle\Entity\Repository\StyleRepository

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    fields:
        slug:
            type: string
            name: slug

        position:
            type: integer
            name: position
            options:
                default: 0

    manyToOne:
        parent:
            targetEntity: Furniture\ProductBundle\Entity\Style
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE

    oneToMany:
        children:
            targetEntity: Furniture\ProductBundle\Entity\Style
            mappedBy: parent

    uniqueConstraints:
        product_style_slug_unique:
            columns: [ slug ]