Furniture\ProductBundle\Entity\TypeTranslation:
    type: entity
    table: product_type_translation

    id:
        id:
            type: integer
            name: id
            generator:
                strategy: AUTO

    fields:
        name:
            name: name
            type: string
