factory_profile:
    path: /
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.dashboard:dashboard

factory_profile_user_relations:
    path: /user-relations
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.user_relation:userRelations

factory_profile_user_relation_create:
    path: /user-relation/create
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.user_relation:edit

factory_profile_user_relation_edit:
    path: /user-relation/{relation}/edit
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales%, relation: \d+ }
    defaults:
        _controller: frontend.controller.factory.user_relation:edit

factory_profile_user_relation_remove:
    path: /user-relation/{relation}/remove
    methods: [ GET ]
    requirements: { _locale: %available_locales%, relation: \d+ }
    defaults:
        _controller: frontend.controller.factory.user_relation:remove

factory_profile_user_relation_approve:
    path: /user-relation/{relation}/approve
    methods: [ GET ]
    requirements: { _locale: %available_locales%, relation: \d+ }
    defaults:
        _controller: frontend.controller.factory.user_relation:approve

factory_profile_default_relation:
    path: /default-relation
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.default_relation:defaultRelation

factory_profile_default_relation_edit:
    path: /default-relation/edit
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.default_relation:edit
        
factory_profile_map_cluser:
    path: /retailer/map
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.user_map:clusterMap