factory_side_list:
    path: /
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory_section:factories
    
factory_side_general:
    path: /{factory}
    methods: [ GET ]
    requirements: { _locale: %available_locales%, factory: \d+ }
    defaults:
        _controller: frontend.controller.factory_section:general

factory_side_news:
    path: /{factory}/news
    methods: [ GET ]
    requirements: { _locale: %available_locales%, factory: \d+ }
    defaults:
        _controller: frontend.controller.factory_section:news

factory_side_news_view:
    path: /{factory}/news/{slug}
    methods: [ GET ]
    requirements: { _locale: %available_locales%, factory: \d+, slug: .+ }
    defaults:
        _controller: frontend.controller.factory_section:post

factory_side_circulars:
    path: /{factory}/circulars
    methods: [ GET ]
    requirements: { _locale: %available_locales%, factory: \d+ }
    defaults:
        _controller: frontend.controller.factory_section:circulars

factory_side_circular:
    path: /{factory}/circular/{slug}
    methods: [ GET ]
    requirements: { _locale: %available_locales%, factory: \d+, slug: .+ }
    defaults:
        _controller: frontend.controller.factory_section:post
