factory_profile:
    path: /
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.dashboard:dashboard

factory_profile_retailer_relations:
    path: /retailer-relations
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.retailer_relation:retailerRelations

factory_profile_retailer_relation_create:
    path: /retailer-relation/create
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.retailer_relation:edit

factory_profile_retailer_relation_edit:
    path: /retailer-relation/{relation}/edit
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales%, relation: \d+ }
    defaults:
        _controller: frontend.controller.factory.retailer_relation:edit

factory_profile_retailer_relation_remove:
    path: /retailer-relation/{relation}/remove
    methods: [ GET ]
    requirements: { _locale: %available_locales%, relation: \d+ }
    defaults:
        _controller: frontend.controller.factory.retailer_relation:remove

factory_profile_retailer_relation_approve:
    path: /user-relation/{relation}/approve
    methods: [ GET ]
    requirements: { _locale: %available_locales%, relation: \d+ }
    defaults:
        _controller: frontend.controller.factory.retailer_relation:approve

factory_profile_default_relation:
    path: /default-relation
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.default_relation:defaultRelation

factory_profile_default_relation_edit:
    path: /default-relation/edit
    methods: [ GET, POST ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.default_relation:edit
        
factory_profile_map_cluser:
    path: /retailer/map
    methods: [ GET ]
    requirements: { _locale: %available_locales% }
    defaults:
        _controller: frontend.controller.factory.user_map:clusterMap