security_login:
    path: /login
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:login

security_login_check:
    path: /login_check

security_logout:
    path: /logout

security_register:
    path: /register
    methods: [ GET, POST ]
    defaults:
        _controller: frontend.controller.security:register

security_register_complete:
    path: /register/complete
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:registerComplete

security_register_complete_reset:
    path: /register/complete/reset
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:resetRegisterComplete

security_reset_password_request:
    path: /reset-password-request
    methods: [ GET, POST ]
    defaults:
        _controller: frontend.controller.security:resetPasswordRequest

security_reset_password_requets_success:
    path: /reset-password-request/success
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:resetPasswordRequestSuccessfully

security_reset_password_request_reset:
    path: /reset-password-request/reset
    methods: [ GET, POST ]
    defaults:
        _controller: frontend.controller.security:resetPasswordRequestReset

security_reset_password:
    path: /reset-password/{token}
    methods: [ GET, POST ]
    requirements: {token: "[a-f0-9]{64}" }
    defaults:
        _controller: frontend.controller.security:resetPassword

security_reset_password_success:
    path: /reset-password/success
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:resetPasswordSuccessfully

security_verify_email:
    path: /verify-email/{token}
    methods: [ GET, POST ]
    requirements: {token: "[a-f0-9]{32}" }
    defaults:
        _controller: frontend.controller.security:verifyEmailRequest

security_verify_success:
    path: /verify-email/success
    methods: [ GET, POST ]
    defaults:
        _controller: frontend.controller.security:verifyEmailSuccess

security_need_reset_password:
    path: /need-reset-password
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:needResetPassword

security_send_need_reset_password:
    path: /need-reset-password/reset/
    methods: [ GET ]
    defaults:
        _controller: frontend.controller.security:sendNeedResetPassword
