Furniture\PostBundle\Entity\PostFile:
    type: entity
    table: post_file

    fields:
        name:
            type: string
            name: name
            nullable: true

    manyToOne:
        post:
            targetEntity: Furniture\PostBundle\Entity\Post
            inversedBy: files
            joinColumn:
                name: post_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
    
    lifecycleCallbacks:
        prePersist: [doSetOriginName]