services:
    furniture.postgressearch.listener:
        class:     Furniture\PostgresSearchBundle\EventListener\SearchListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
