#Factory admin routes
furniture_backend_factory_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: Furniture.controller.factory:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Factory:index.html.twig
            
furniture_backend_factory_create:
    path: /new
    methods: [ GET, POST ]
    defaults:
        _controller: Furniture.controller.factory:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Factory:create.html.twig
            redirect: furniture_backend_factory_show
            form: Furniture\FactoryBundle\Form\Type\FactoryType
            
furniture_backend_factory_update:
    path: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: Furniture.controller.factory:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/Factory:update.html.twig
            form: Furniture\FactoryBundle\Form\Type\FactoryType
            redirect: furniture_backend_factory_show
            
furniture_backend_factory_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: Furniture.controller.factory:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Factory:show.html.twig
    
furniture_backend_factory_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: Furniture.controller.factory:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: furniture_backend_factory_index
#Factory user relation admin routes
furniture_backend_factory_user_relation_index:
    path: /{id}/edit/userrelation
    methods: [ GET ]
    defaults:
        _controller: Furniture.controller.factory_user_relation:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/FactoryRetailerRelation:index.html.twig
            criteria: { factory: $id }
            
furniture_backend_factory_user_relation_create:
    path: /{id}/edit/userrelation/new
    methods: [ GET, POST ]
    defaults:
        _controller: Furniture.controller.factory_user_relation:createAction
        _sylius:
            template: SyliusWebBundle:Backend/FactoryRetailerRelation:create.html.twig
            redirect: 
                route: furniture_backend_factory_user_relation_index
                parameters: { id: $id }
            form: Furniture\FactoryBundle\Form\Type\FactoryRetailerRelationType
            
furniture_backend_factory_user_relation_update:
    path: /{id}/edit/{rid}
    methods: [GET, PUT]
    defaults:
        _controller: Furniture.controller.factory_user_relation:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/FactoryRetailerRelation:update.html.twig
            form: Furniture\FactoryBundle\Form\Type\FactoryRetailerRelationType
            redirect: 
                route: furniture_backend_factory_user_relation_index
                parameters: { id: $id }
            
furniture_backend_factory_user_relation_delete:
    path: /{fid}/userrelation/{id}
    methods: [DELETE]
    defaults:
        _controller: Furniture.controller.factory_user_relation:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: 
                route: furniture_backend_factory_user_relation_index
                parameters: { id: $fid }
                
furniture_backend_factory_referal_key_index:
    path: /{fid}/referal
    methods: [ GET ]
    defaults:
        _controller: Furniture.controller.factory_referal_key:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/FactoryReferalKey:index.html.twig
            criteria: { factory: $fid }
 
furniture_backend_factory_referal_key_create:
    path: /{fid}/referal/create
    methods: [ GET, POST ]
    defaults:
        _controller: Furniture.controller.factory_referal_key:createAction
        _sylius:
            template: SyliusWebBundle:Backend/FactoryReferalKey:create.html.twig
            criteria: { factory: $fid }
                      
            
furniture_backend_factory_referal_key_update:
    path: /{fid}/referal/{id}
    methods: [ GET, PUT ]
    defaults:
        _controller: Furniture.controller.factory_referal_key:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/FactoryReferalKey:update.html.twig
            form: Furniture\FactoryBundle\Form\Type\FactoryReferalKeyType
            redirect: 
                route: furniture_backend_factory_referal_key_index
                parameters: {'fid': $fid}
                
furniture_backend_factory_referal_key_delete:
    path: /{fid}/referal/{id}
    methods: [ DELETE ]
    defaults:
        _controller: Furniture.controller.factory_referal_key:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: 
                route: furniture_backend_factory_referal_key_index
                parameters: {'fid': $fid}
