furniture_backend_product_best_sellers_index:
    path: /
    defaults:
        _controller: furniture.controller.product_best_sellers:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/BestSellers:index.html.twig

furniture_backend_product_best_sellers_create:
    path: /new
    defaults:
        _controller: furniture.controller.product_best_sellers:createAction
        _sylius:
            template: SyliusWebBundle:Backend/BestSellers:create.html.twig

furniture_backend_product_best_sellers_update:
    path: /{id}/update
    requirements: { id: \d+ }
    defaults:
        _controller: furniture.controller.product_best_sellers:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/BestSellers:update.html.twig

furniture_backend_product_best_sellers_delete:
    path: /{id}/delete
    requirements: { id: \d+ }
    defaults:
        _controller: furniture.controller.product_best_sellers:deleteAction
