furniture_backend_product_category:
    path: /
    methods: [ GET ]
    defaults:
        _controller: furniture.controller.product_category:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/ProductCategory:index.html.twig
            paginate: 9999

furniture_backend_product_category_create:
    path: /new
    methods: [ GET, POST ]
    defaults:
        _controller: furniture.controller.product_category:createAction
        _sylius:
            template: SyliusWebBundle:Backend/ProductCategory:create.html.twig
            form: Furniture\ProductBundle\Form\Type\CategoryType
            redirect: furniture_backend_product_category

furniture_backend_product_category_update:
    path: /{id}/update
    methods: [ GET, POST ]
    defaults:
        _controller: furniture.controller.product_category:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/ProductCategory:update.html.twig
            form: Furniture\ProductBundle\Form\Type\CategoryType
            redirect: furniture_backend_product_category

furniture_backend_product_category_delete:
    path: /{id}/delete
    methods: [ DELETE ]
    defaults:
        _controller: furniture.controller.product_category:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: furniture_backend_product_category