furniture_backend_product_space:
    path: /
    methods: [ GET ]
    defaults:
        _controller: furniture.controller.product_space:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/ProductSpace:index.html.twig
            paginate: 9999
            sortable: true
            sorting:
                position: ASC

furniture_backend_product_space_create:
    path: /new
    methods: [ GET, POST ]
    defaults:
        _controller: furniture.controller.product_space:createAction
        _sylius:
            template: SyliusWebBundle:Backend/ProductSpace:create.html.twig
            form: Furniture\ProductBundle\Form\Type\SpaceType
            redirect: furniture_backend_product_space

furniture_backend_product_space_update:
    path: /{id}/update
    methods: [ GET, POST ]
    defaults:
        _controller: furniture.controller.product_space:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/ProductSpace:update.html.twig
            form: Furniture\ProductBundle\Form\Type\SpaceType
            redirect: furniture_backend_product_space

furniture_backend_product_space_delete:
    path: /{id}/delete
    methods: [ DELETE ]
    defaults:
        _controller: furniture.controller.product_space:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: furniture_backend_product_space

furniture_backend_product_space_sort_positions:
    path: /sort-positions
    methods: [ POST ]
    defaults:
        _controller: furniture.controller.product_space:sortPositionsAction
