services:
    pricing.calculator:
        class: Furniture\PricingBundle\Calculator\PriceCalculator
        arguments:
            - @security.token_storage
            - @doctrine.orm.default_entity_manager
    
    pricing.twig_extension:
        class: Furniture\PricingBundle\Twig\PricingExtension
        arguments:
            - @pricing.calculator
            - @sylius.context.currency
            - @sylius.templating.helper.money
            - @product_pattern.product_variant_price_compiller
        tags:
            - { name: twig.extension }
